-- Chemistry chapter 7 — 75 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Chemistry' and c.seq = 7
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Chemistry chapter 7: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A reaction in which oxidation and reduction occur simultaneously is called:', '["Neutralization reaction","Decomposition reaction","Redox reaction","Displacement reaction"]'::jsonb, 'C', 1, '89f7df12cf96', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of an element in its free state is:', '["+1","–1","0","+2"]'::jsonb, 'C', 1, 'd2102c9e36af', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is oxidized in the reaction Zn + CuSO₄ → ZnSO₄ + Cu?', '["Copper","Sulphate ion","Zinc","Oxygen"]'::jsonb, 'C', 1, '78de46a4f57a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The substance that gains electrons is called:', '["Oxidizing agent","Reducing agent","Catalyst","Electrolyte"]'::jsonb, 'A', 1, '10a3332a520f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of sodium in NaCl is:', '["–1","0","+1","+2"]'::jsonb, 'C', 1, 'f1e502c127b3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In a neutral compound, the sum of oxidation numbers is:', '["+1","–1","0","+2"]'::jsonb, 'C', 1, 'e8d3007e65ea', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which process causes rusting of iron?', '["Reduction","Corrosion","Neutralization","Distillation"]'::jsonb, 'B', 1, '482326016f38', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Rust mainly consists of:', '["Iron sulphide","Hydrated iron oxide","Iron chloride","Iron carbonate"]'::jsonb, 'B', 1, '40c39a1404fd', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of oxygen is usually:', '["+2","–2","+1","0"]'::jsonb, 'B', 1, '1924fd80a9a6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which substance acts as a reducing agent?', '["One that loses electrons","One that gains electrons","One that gains oxygen","One that loses hydrogen"]'::jsonb, 'A', 1, '1e09621ed5a0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of hydrogen in most compounds is:', '["–1","+1","0","+2"]'::jsonb, 'B', 1, '2980d3e52e30', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is a method to prevent corrosion?', '["Heating","Painting","Grinding","Washing with water"]'::jsonb, 'B', 1, '67a0c09b572b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Galvanization involves coating iron with:', '["Copper","Aluminium","Zinc","Silver"]'::jsonb, 'C', 1, '4e6785547b4a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which metal is commonly used for sacrificial protection of ships?', '["Silver","Gold","Magnesium","Copper"]'::jsonb, 'C', 1, '3799b36b0969', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In electroplating, the object to be plated acts as:', '["Cathode","Anode","Electrolyte","Salt bridge"]'::jsonb, 'A', 1, '8eb25c1a59eb', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of chlorine in NaCl is:', '["+1","–1","0","+2"]'::jsonb, 'B', 1, 'fa526851b465', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which statement is true about oxidation?', '["Gain of electrons","Decrease in oxidation number","Loss of electrons","Gain of hydrogen"]'::jsonb, 'C', 1, '14fe9a81e883', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is reduced?', '["Substance losing electrons","Substance gaining electrons","Substance gaining oxygen","Substance losing hydrogen"]'::jsonb, 'B', 1, 'e5372e4677b3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Corrosion of iron requires:', '["Water only","Oxygen only","Air and moisture","Sunlight only"]'::jsonb, 'C', 1, 'a2cbb2be117e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which compound has oxygen with oxidation number –1?', '["H₂O","Na₂O","H₂O₂","CO₂"]'::jsonb, 'C', 1, 'cad59cd35c3d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of calcium in CaCl₂ is:', '["–2","+1","+2","0"]'::jsonb, 'C', 1, '5c15eecb6e7a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The process of coating one metal with another using electricity is:', '["Galvanization","Electroplating","Distillation","Sublimation"]'::jsonb, 'B', 1, 'feb535fd7a29', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which gas is involved in rust formation?', '["Nitrogen","Hydrogen","Oxygen","Chlorine"]'::jsonb, 'C', 1, 'c16ec4508c9c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the reaction CuO + H₂ → Cu + H₂O, CuO is:', '["Oxidized","Reduced","Neutralized","Hydrolyzed"]'::jsonb, 'B', 1, 'dc9c964914af', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of sulphur in H₂SO₄ is:', '["+6","+4","–2","0"]'::jsonb, 'A', 1, 'e99ddc24c17e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following prevents direct contact of iron with air?', '["Rusting","Corrosion","Painting","Heating"]'::jsonb, 'C', 1, 'b126ea55add2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of aluminium in Al₂O₃ is:', '["+3","–3","+2","0"]'::jsonb, 'A', 1, '9d227f1013e7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which reaction is a redox reaction?', '["HCl + NaOH → NaCl + H₂O","Zn + CuSO₄ → ZnSO₄ + Cu","AgNO₃ + NaCl → AgCl + NaNO₃","CaCO₃ → CaO + CO₂"]'::jsonb, 'B', 1, '69c8d546a854', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is not a method of corrosion prevention?', '["Painting","Oiling","Galvanizing","Rusting"]'::jsonb, 'D', 1, 'dd49ef562fda', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In electrochemistry, electron transfer takes place during:', '["Physical changes","Redox reactions","Boiling","Melting"]'::jsonb, 'B', 1, '3613e7e0d08c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of potassium in KNO₃ is:', '["–1","+1","+2","0"]'::jsonb, 'B', 1, '5cc222c20e5f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which substance is oxidized in the reaction 2Mg + O₂ → 2MgO?', '["Oxygen","Magnesium","Magnesium oxide","None"]'::jsonb, 'B', 1, 'f869e70ef64e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of fluorine is always:', '["+1","–1","0","+2"]'::jsonb, 'B', 1, '5e07d8bd6ac6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which metal corrodes to form a green layer?', '["Iron","Zinc","Copper","Silver"]'::jsonb, 'C', 1, '97fa9c39bf06', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The sum of oxidation numbers in an ion is equal to:', '["Zero","Number of atoms","Charge on the ion","Number of electrons"]'::jsonb, 'C', 1, 'ad345c44db62', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the reaction Fe₂O₃ + 3CO → 2Fe + 3CO₂, CO acts as:', '["Oxidizing agent","Reducing agent","Catalyst","Electrolyte"]'::jsonb, 'B', 1, '34aef21fc786', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The brown coating formed on iron is called:', '["Tarnish","Scale","Rust","Slag"]'::jsonb, 'C', 1, '9c6fba6e062a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The oxidation number of nitrogen in NH₃ is:', '["–3","+3","+5","0"]'::jsonb, 'A', 1, 'b23a49241ab0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which method uses a more reactive metal for protection?', '["Electroplating","Sacrificial protection","Painting","Oiling"]'::jsonb, 'B', 1, '53771e9a9d52', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In electroplating of silver, the electrolyte contains:', '["Silver ions","Iron ions","Copper ions","Zinc ions"]'::jsonb, 'A', 1, '37ffd04b91fa', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which one is an example of oxidation?', '["CuO → Cu","H₂ → 2H⁺ + 2e⁻","Cl₂ + 2e⁻ → 2Cl⁻","N₂ + 3H₂ → 2NH₃"]'::jsonb, 'B', 1, '2ee94cd8649c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The Roman numeral in iron (III) oxide shows:', '["Atomic mass","Number of atoms","Oxidation number","Valency of oxygen"]'::jsonb, 'C', 1, 'bbc44798f70e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Electrochemistry mainly deals with:', '["Heat changes","Light energy","Chemical reactions involving electricity","Nuclear reactions"]'::jsonb, 'C', 1, 'be66509adb55', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In which reaction is oxygen removed from a compound?', '["2Mg + O₂ → 2MgO","CuO + H₂ → Cu + H₂O","Fe + S → FeS","Na + Cl₂ → NaCl"]'::jsonb, 'B', 1, 'f354ab8ca26b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A reducing agent in a reaction:', '["Gains electrons itself","Causes another substance to lose electrons","Causes reduction of another substance","Always contains oxygen"]'::jsonb, 'C', 1, '3fc2a0e5fcfe', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'An iron gate near the sea rusts faster than the same gate in a dry city. The main reason is:', '["Higher temperature near sea","Presence of salty moisture","Lack of oxygen","Excess sunlight"]'::jsonb, 'B', 1, '4e7ac1981374', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student places a clean iron nail in copper sulphate solution. After some time, a brown layer appears on the nail. This shows that iron:', '["Is reduced","Is less reactive than copper","Displaces copper from solution","Prevents oxidation"]'::jsonb, 'C', 1, 'c3f78fa4c52a', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During electroplating of a spoon with silver, the spoon is connected to the:', '["Anode","Cathode","Salt bridge","Positive terminal only"]'::jsonb, 'B', 1, '111ff5cd6d30', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A metal object is painted before being used outdoors. The paint mainly:', '["Increases conductivity","Prevents contact with air and moisture","Speeds up oxidation","Reduces weight of metal"]'::jsonb, 'B', 1, '703aa410fbeb', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A ship made of iron is protected by attaching blocks of magnesium. Magnesium protects iron because it:', '["Is less reactive than iron","Reacts first with oxygen","Prevents water evaporation","Forms alloy with iron"]'::jsonb, 'B', 1, '91c186f7cf35', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student observes that copper metal does not react with zinc sulphate solution. This indicates that copper is:', '["More reactive than zinc","Less reactive than zinc","Equal in reactivity to zinc","An oxidizing agent"]'::jsonb, 'B', 1, 'abfa146d463d', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During rusting, iron undergoes:', '["Reduction","Oxidation","Neutralization","Polymerization"]'::jsonb, 'B', 1, '82b75a70e959', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A silver ring becomes black after long exposure to air. This is an example of:', '["Distillation","Corrosion","Neutralization","Electrolysis"]'::jsonb, 'B', 1, '8555bb7899bc', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A reaction vessel contains hydrogen gas reacting with copper oxide. If copper oxide changes into copper, copper oxide has:', '["Been oxidized","Lost oxygen","Gained electrons from copper","Increased oxidation number"]'::jsonb, 'B', 1, '070906fce5f6', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student accidentally scratches the zinc coating on galvanized iron. The iron still remains protected because zinc:', '["Is decorative","Acts as sacrificial metal","Is non-reactive","Absorbs moisture"]'::jsonb, 'B', 1, '4001f610c9f5', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which situation best represents oxidation?', '["Gain of electrons by chlorine","Removal of oxygen from copper oxide","Loss of electrons by magnesium","Formation of water"]'::jsonb, 'C', 1, 'fe0e1ffc830a', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'An electroplated object receives metal coating because metal ions:', '["Move toward cathode and gain electrons","Move toward anode and lose electrons","React with oxygen","Evaporate during process"]'::jsonb, 'A', 1, 'a0e514da6caa', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemical reaction increases the oxidation number of sulphur from +4 to +6. Sulphur has:', '["Been reduced","Been oxidized","Lost oxygen","Gained hydrogen"]'::jsonb, 'B', 1, '8bb5a0b30647', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student keeps one iron nail in dry air and another in moist air. Which nail rusts faster?', '["Nail in dry air","Nail in moist air","Both equally","Neither rusts"]'::jsonb, 'B', 1, 'c3af6c75f7fe', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In electrochemistry, the movement of electrons takes place:', '["Through solution only","From cathode to anode inside solution","During redox reactions","Only in acids"]'::jsonb, 'C', 1, '4a63e8feffcc', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A laboratory technician coats iron with chromium to make it shiny and corrosion resistant. This process is:', '["Rusting","Distillation","Electroplating","Refining"]'::jsonb, 'C', 1, '4b309c64d07c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Iron pipes buried underground are often attached with magnesium strips. This method is called:', '["Galvanization","Electrolysis","Sacrificial protection","Neutralization"]'::jsonb, 'C', 1, 'a006738d77e3', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student notices bubbles during an electrochemical experiment. The bubbles indicate:', '["Gas formation due to chemical reaction","Melting of metal","Rust prevention","Physical change only"]'::jsonb, 'A', 1, '1ab2e30f76f2', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student wants to protect an iron bicycle from rusting. Which method is most suitable?', '["Heating regularly","Keeping in sunlight","Painting surface","Washing with salt water"]'::jsonb, 'C', 1, 'dfc70e88507c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A reaction causes copper ions to gain electrons and form copper metal. Copper ions are:', '["Oxidized","Reduced","Neutralized","Corroded"]'::jsonb, 'B', 1, '5417586c5acc', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student compares rusting in distilled water and salty water. Rusting is faster in salty water because:', '["Salt decreases conductivity","Salt increases chemical activity","Salt removes oxygen","Salt prevents oxidation"]'::jsonb, 'B', 1, '7b04b0f06b68', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A metal spoon coated with silver becomes shiny because silver:', '["Absorbs light","Is highly reflective","Prevents oxidation completely","Removes impurities"]'::jsonb, 'B', 1, '5a5278d83c73', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemical engineer wants to prevent corrosion in machinery. Which method is least effective?', '["Painting","Oiling","Exposure to moisture","Galvanization"]'::jsonb, 'C', 1, '83bff7ec5497', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which statement best explains sacrificial protection?', '["Less reactive metal protects more reactive metal","More reactive metal corrodes instead of iron","Iron reacts first with oxygen","Oxygen is removed from atmosphere"]'::jsonb, 'B', 1, 'b79440282c92', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student heats copper oxide with carbon. Copper oxide changes into copper because carbon:', '["Oxidizes copper","Acts as reducing agent","Prevents electron transfer","Absorbs copper"]'::jsonb, 'B', 1, '9e58b09ca897', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During electroplating of gold on jewelry, gold ions:', '["Lose electrons and deposit","Gain electrons and deposit","React with oxygen first","Evaporate from solution"]'::jsonb, 'B', 1, 'dd8f0991ddec', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student notices that aluminium does not corrode quickly despite being reactive. This is because aluminium:', '["Is non-metallic","Forms protective oxide layer","Does not react with oxygen","Is less reactive than iron"]'::jsonb, 'B', 1, 'a3ef4bd4f33d', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student passes hydrogen gas over hot copper oxide and notices formation of reddish-brown copper. Which statement is correct?', '["Hydrogen is reduced","Copper oxide is oxidized","Hydrogen acts as reducing agent","Copper gains oxygen"]'::jsonb, 'C', 1, '673a7d17a298', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During electroplating of a bicycle handle with chromium, the handle is connected to the negative terminal of the battery. Why?', '["To allow chromium ions to gain electrons","To oxidize chromium metal","To remove electrons from handle","To increase rusting speed"]'::jsonb, 'A', 1, 'f1e28285ab1f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'CuO+CO→Cu+CO₂ carbon monoxide is called a reducing agent because it:', '["Gains oxygen","Removes oxygen from CuO","Loses electrons to oxygen only","Changes into copper"]'::jsonb, 'B', 1, 'c09c090d45c3', null);
end $$;
