-- Chemistry chapter 10 — 85 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Chemistry' and c.seq = 10
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Chemistry chapter 10: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'According to Arrhenius theory, an acid produces which ion in water?', '["OH⁻","H⁺","Na⁺","Cl⁻"]'::jsonb, 'B', 1, '5db8c2c1c065', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'According to Arrhenius theory, a base produces which ion in water?', '["H⁺","Cl⁻","OH⁻","Na⁺"]'::jsonb, 'C', 1, '4034c918cd00', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which scientist proposed the Arrhenius theory of acids and bases?', '["Dalton","Rutherford","Arrhenius","Bohr"]'::jsonb, 'C', 1, 'a0777954ed9e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Acids generally have a ______ taste.', '["Bitter","Sweet","Sour","Salty"]'::jsonb, 'C', 1, 'b411b44461d8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Bases generally have a ______ taste.', '["Sour","Bitter","Sweet","Salty"]'::jsonb, 'B', 1, 'ce5b94287849', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'An acid turns blue litmus paper:', '["Green","Yellow","Red","Black"]'::jsonb, 'C', 1, 'e8b019122089', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A base turns red litmus paper:', '["Blue","Green","Yellow","Red"]'::jsonb, 'A', 1, '697a2dcc94b9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is a common acid?', '["NaOH","KOH","HCl","Ca(OH)₂"]'::jsonb, 'C', 1, 'f756c3f81746', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is a common base?', '["HNO₃","H₂SO₄","H₃PO₄","NaOH"]'::jsonb, 'D', 1, 'ecbc0a46e079', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Sodium hydroxide is commonly used in:', '["Soap making","Photography","Food preservation","Medicine"]'::jsonb, 'A', 1, 'b1a718fb149e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Potassium hydroxide is used in making:', '["Cement","Liquid soap","Fertilizers","Paints"]'::jsonb, 'B', 1, 'fe9499240d73', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Calcium hydroxide is used in making:', '["Mortar and cement","Explosives","Soft drinks","Perfumes"]'::jsonb, 'A', 1, '245acf909b65', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Magnesium hydroxide is commonly used as:', '["Fuel","Fertilizer","Antacid","Dye"]'::jsonb, 'C', 1, '547507a44fde', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A Bronsted-Lowry acid is a:', '["Proton acceptor","Electron donor","Proton donor","Salt former"]'::jsonb, 'C', 1, 'bd6b127d8fa0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A Bronsted-Lowry base is a:', '["Proton acceptor","Proton donor","Metal oxide","Salt"]'::jsonb, 'A', 1, '745167de9d69', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the reaction HCl + H₂O → H₃O⁺ + Cl⁻, HCl acts as:', '["Base","Acid","Salt","Catalyst"]'::jsonb, 'B', 1, '3c9a8efdbfb2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the reaction HCl + H₂O → H₃O⁺ + Cl⁻, water acts as:', '["Acid","Salt","Base","Metal"]'::jsonb, 'C', 1, '5344cea57eee', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the reaction H₂O + NH₃ → NH₄⁺ + OH⁻, NH₃ acts as:', '["Acid","Base","Salt","Indicator"]'::jsonb, 'B', 1, '0ea45b7b9787', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the reaction H₂O + NH₃ → NH₄⁺ + OH⁻, water acts as:', '["Acid","Base","Salt","Alkali"]'::jsonb, 'A', 1, '10f63137594e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Water can behave as both an acid and a base. Such substances are called:', '["Neutral","Amphoteric","Basic","Acidic"]'::jsonb, 'B', 1, '51107df6bc30', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is an amphoteric substance?', '["HCl","NaOH","H₂O","HNO₃"]'::jsonb, 'C', 1, 'f18d3f92c51f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which acid is used in the manufacture of fertilizers and explosives?', '["HCl","H₃PO₄","HNO₃","CH₃COOH"]'::jsonb, 'C', 1, '97e2584dc751', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Hydrochloric acid is commonly used for:', '["Cleaning metals","Making cement","Food preservation","Photography"]'::jsonb, 'A', 1, '0e32833b035b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Acids and bases in aqueous solutions can:', '["Conduct electricity","Produce light","Float on water","Become gases"]'::jsonb, 'A', 1, '4f3ec707194a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which ion is responsible for acidic properties?', '["Na⁺","OH⁻","H⁺","Cl⁻"]'::jsonb, 'C', 1, '5be61997584e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which ion is responsible for basic properties?', '["H⁺","OH⁻","NO₃⁻","SO₄²⁻"]'::jsonb, 'B', 1, '42eaa9482ef2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'NaOH dissociates in water to form:', '["H⁺ and OH⁻","Na⁺ and OH⁻","Na⁺ and Cl⁻","H⁺ and Cl⁻"]'::jsonb, 'B', 1, '47e99b433142', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'HCl dissociates in water to form:', '["H⁺ and Cl⁻","H⁺ and OH⁻","Na⁺ and Cl⁻","K⁺ and OH⁻"]'::jsonb, 'A', 1, '5fbf8a0d6e17', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is a base?', '["H₂SO₄","HNO₃","NH₄OH","HCl"]'::jsonb, 'C', 1, '5e501e38ac7b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is an acid?', '["KOH","NaOH","Ca(OH)₂","H₃PO₄"]'::jsonb, 'D', 1, '2f70a04aea22', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which acid is used as an acidulant in food?', '["HCl","HNO₃","H₂SO₄","H₃PO₄"]'::jsonb, 'D', 1, '2853a82afaf2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Bases that are soluble in water are called:', '["Acids","Alkalis","Salts","Oxides"]'::jsonb, 'B', 1, '996313cef2f5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is an alkali?', '["NaOH","CuO","CO₂","SO₂"]'::jsonb, 'A', 1, 'bcd7b7f8f353', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A substance that accepts a proton forms a:', '["Negative ion","Positive ion","Neutral atom","Molecule only"]'::jsonb, 'B', 1, '4d6f37aff4fd', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 1, 'After donating a proton, an acid usually forms a:', '["Positive ion","Neutral atom","Negative ion","Molecule"]'::jsonb, 'C', 1, '91180e48128f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is NOT a property of acids?', '["Sour taste","Turn blue litmus red","Produce H⁺ ions in water","Turn red litmus blue"]'::jsonb, 'D', 1, '83e21425fbb8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is NOT a property of bases?', '["Bitter taste","Produce OH⁻ ions in water","Turn red litmus blue","Turn blue litmus red"]'::jsonb, 'D', 1, '279b9c4bc718', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'NH₃ behaves as a base because it:', '["Donates electrons","Accepts a proton","Produces Cl⁻ ions","Produces H⁺ ions directly"]'::jsonb, 'B', 1, 'd88940314b8d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which acid is commonly present in laboratory cleaning solutions?', '["Hydrochloric acid","Sodium hydroxide","Potassium hydroxide","Calcium hydroxide"]'::jsonb, 'A', 1, '681ba6d36edd', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The Bronsted-Lowry theory defines acids and bases in terms of:', '["Electrons","Neutrons","Protons","Atoms"]'::jsonb, 'C', 1, 'e3f38bd21379', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which pair correctly represents an acid and a base respectively?', '["HCl and NaOH","NaOH and HNO₃","KOH and H₂SO₄","NH₄OH and HCl"]'::jsonb, 'A', 1, '503a584a347d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following acids is used in the manufacture of many chemicals, dyes, and paints?', '["HCl","H₂SO₄","HNO₃","H₃PO₄"]'::jsonb, 'B', 1, '962a79c651d2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The study of acids, bases, and their reactions helps explain:', '["Only physical changes","Only nuclear reactions","Many everyday chemical processes","Only biological reactions"]'::jsonb, 'C', 1, '56e62ca05bc5', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student places blue litmus paper into an unknown solution. The paper immediately turns red. The solution most likely contains:', '["OH⁻ ions","H⁺ ions","Na⁺ ions","Cl⁻ ions"]'::jsonb, 'B', 1, '969ab008d5a8', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During an experiment, a solution changes red litmus paper to blue. According to Arrhenius theory, the solution contains a high concentration of:', '["H⁺ ions","H₃O⁺ ions","OH⁻ ions","Cl⁻ ions"]'::jsonb, 'C', 1, '00ba0cded567', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A factory uses a chemical to remove rust from iron surfaces. Which acid is most likely being used?', '["H₃PO₄","HCl","NH₄OH","Mg(OH)₂"]'::jsonb, 'B', 1, '3e3ce208f95d', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A patient complains of stomach acidity. The doctor recommends milk of magnesia. This substance works because it is a:', '["Strong acid","Salt","Base","Metal oxide"]'::jsonb, 'C', 1, '94262debe247', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemist adds ammonia to water. The ammonia molecule accepts a proton from water. According to Bronsted-Lowry theory, ammonia behaves as a:', '["Salt","Acid","Base","Catalyst"]'::jsonb, 'C', 1, '1ed13e4f823b', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student accidentally spills a solution on red litmus paper, but no color change occurs. Which statement is most likely correct?', '["The solution is acidic","The solution is basic","The solution may be neutral","The solution contains only H⁺ ions"]'::jsonb, 'C', 1, 'accd917c4645', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A farmer applies a chemical containing phosphoric acid to improve crop growth. The acid is mainly used in the manufacture of:', '["Detergents","Fertilizers","Plastics","Dyes"]'::jsonb, 'B', 1, 'afc4f70f4e2f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In the reaction HCl + H₂O → H₃O⁺ + Cl⁻, the water molecule acts as a proton:', '["Donor","Acceptor","Producer","Neutralizer"]'::jsonb, 'B', 1, '14d1e02217a0', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student observes that a substance has a bitter taste and turns red litmus blue. The substance is most likely:', '["An acid","A salt","A base","A metal"]'::jsonb, 'C', 1, 'ff98bdffcc23', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During an industrial process, nitric acid is selected because of its role in producing fertilizers and explosives. Its chemical formula is:', '["H₂SO₄","HCl","HNO₃","H₃PO₄"]'::jsonb, 'C', 1, 'c46ebf634576', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A solution contains a large number of OH⁻ ions. Which observation would be expected?', '["Blue litmus turns red","Red litmus turns blue","Sour taste","Release of H⁺ ions"]'::jsonb, 'B', 1, '54d7ad31d427', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemist identifies a substance as amphoteric. Which behavior confirms this property?', '["It reacts only as an acid","It reacts only as a base","It can act as both an acid and a base","It does not react at all"]'::jsonb, 'C', 1, '60d780fe667a', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A laboratory technician is preparing liquid soap. Which base would be most suitable?', '["Ca(OH)₂","Mg(OH)₂","KOH","HCl"]'::jsonb, 'C', 1, 'f806459e2d43', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student is given four unlabeled bottles containing HCl, HNO₃, NaOH, and KOH. Which two substances will turn red litmus paper blue?', '["HCl and HNO₃","HCl and KOH","NaOH and KOH","HNO₃ and NaOH"]'::jsonb, 'C', 1, '6f62535a504a', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemical engineer needs a compound for making mortar. Which substance should be selected?', '["HNO₃","HCl","Ca(OH)₂","NH₄OH"]'::jsonb, 'C', 1, 'fc149fb68361', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student claims that all proton donors are bases. Which observation disproves the claim?', '["HCl donates a proton and acts as an acid","NH₃ accepts a proton","NaOH releases OH⁻ ions","Water is neutral"]'::jsonb, 'A', 1, 'ad4bce916ba6', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A sample solution conducts electricity and turns blue litmus red. The solution most likely contains:', '["H⁺ ions","OH⁻ ions","Na⁺ ions only","Neutral molecules only"]'::jsonb, 'A', 1, 'b4cec7fe2ceb', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During a reaction, a molecule gains a proton. According to Bronsted-Lowry theory, that molecule is acting as a:', '["Acid","Salt","Base","Metal"]'::jsonb, 'C', 1, 'd6c33ce737a5', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A scientist is studying substances that release H⁺ ions in water. Which theory is being applied?', '["Atomic theory","Arrhenius theory","Kinetic theory","Molecular theory"]'::jsonb, 'B', 1, '988f70a2871b', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A bottle is labeled "alkali." Which property must the substance possess?', '["Soluble base","Insoluble base","Strong acid","Neutral salt"]'::jsonb, 'A', 1, '223b32c198b1', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'While studying acids, a student finds a substance used in food and soft drinks. The substance is most likely:', '["HCl","H₂SO₄","H₃PO₄","NaOH"]'::jsonb, 'C', 1, 'cf290ba32a5e', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A solution causes skin irritation and has a sour taste. Which group does it belong to?', '["Bases","Acids","Salts","Metals"]'::jsonb, 'B', 1, '0980f0421de1', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student wants to verify whether a solution is basic. Which indicator result would confirm this?', '["Blue litmus becomes red","Red litmus becomes blue","Red litmus remains red in all cases","Blue litmus becomes colorless"]'::jsonb, 'B', 1, 'fbc00160529a', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a reaction, NH₃ becomes NH₄⁺. This indicates that NH₃ has:', '["Lost a proton","Gained a proton","Lost an electron only","Gained a neutron"]'::jsonb, 'B', 1, 'bcdca8b3c137', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A technician handling laboratory chemicals notices that a solution contains H⁺ ions but no OH⁻ ions. The solution is most likely:', '["Acidic","Basic","Neutral","Amphoteric"]'::jsonb, 'A', 1, '628dc9e76b2c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which substance can behave as both proton donor and proton acceptor depending on conditions?', '["HCl","NaOH","H₂O","HNO₃"]'::jsonb, 'C', 1, 'c4d3485b0a3c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which pair consists entirely of bases?', '["HCl and HNO₃","H₂SO₄ and H₃PO₄","NaOH and KOH","HCl and NaOH"]'::jsonb, 'C', 1, 'beb3ff338601', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A substance accepts H⁺ from another substance and forms a positive ion. It is acting as a:', '["Salt","Acid","Base","Catalyst"]'::jsonb, 'C', 1, '6c25468f1287', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which observation indicates the presence of an alkali rather than merely a base?', '["It reacts with acids","It contains OH⁻ ions","It is soluble in water","It turns red litmus blue"]'::jsonb, 'C', 1, 'a734902228bd', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemical sample acts as an acid in one reaction and as a base in another. The sample is:', '["Neutral","Amphoteric","Metallic","Inert"]'::jsonb, 'B', 1, 'b875d46ef5a7', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemistry student concludes that a solution is basic because it contains excess OH⁻ ions and changes indicator color accordingly. Which indicator observation supports this conclusion?', '["Blue litmus → Red","Red litmus → Blue","Blue litmus → White","Red litmus → Yellow"]'::jsonb, 'B', 1, '948c70e32e10', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'An unknown oxide reacts with water to produce a solution that turns red litmus blue. The oxide is most likely:', '["Acidic oxide","Neutral oxide","Basic oxide","Amphoteric oxide"]'::jsonb, 'C', 1, '4de8fefef54f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Magnesium oxide is added to water. The resulting solution becomes slightly basic. This occurs because magnesium oxide is a:', '["Non-metal oxide","Acidic oxide","Basic oxide","Neutral oxide"]'::jsonb, 'C', 1, 'ec601fea3558', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'When calcium oxide is mixed with water, the resulting solution turns red litmus blue. Which ion is mainly responsible for this behavior?', '["H⁺","Cl⁻","OH⁻","Ca²⁺"]'::jsonb, 'C', 1, 'c24e41c172a3', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student adds dilute HCl to magnesium ribbon. Gas bubbles are produced. The gas evolved is:', '["Oxygen","Carbon dioxide","Hydrogen","Chlorine"]'::jsonb, 'C', 1, '64b791b9ac2c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student adds dilute HCl to marble chips (CaCO₃). Which set of products is formed?', '["Salt + Water","Salt + Hydrogen","Salt + Water + Carbon dioxide","Salt + Oxygen + Water"]'::jsonb, 'C', 1, '10af87c2239c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A teacher asks why carbon dioxide is produced when acids react with carbonates but not when acids react with metals. The best explanation is:', '["Metals contain no carbon atoms","Metals are insoluble","Carbonates contain CO₃²⁻ ions","Acids cannot react with metals"]'::jsonb, 'C', 1, '9e0fcf0e3ab6', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student mixes HCl and NaOH solutions. No gas is evolved, but the solution becomes warm. This indicates:', '["Neutralization reaction occurred","Decomposition reaction occurred","Oxidation occurred","Carbonation occurred"]'::jsonb, 'A', 1, '471f8f409c5f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student accidentally spills NaOH solution on a surface contaminated with dilute HCl. The resulting reaction mainly produces:', '["Salt and water","Hydrogen gas","Carbon dioxide","Oxygen gas"]'::jsonb, 'A', 1, '19a44d6d985c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student heats a mixture of ammonium chloride and sodium hydroxide. A pungent gas is evolved. The gas is:', '["Hydrogen","Carbon dioxide","Ammonia","Oxygen"]'::jsonb, 'C', 1, '9bec9a601273', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A gas produced from heating NH₄Cl and NaOH turns moist red litmus paper blue. The gas is:', '["CO₂","NH₃","H₂","O₂"]'::jsonb, 'B', 1, '1ce29deb5bc4', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which reaction would definitely produce ammonia gas?', '["HCl + Mg","HCl + Na₂CO₃","NaOH + NH₄Cl","HCl + NaOH"]'::jsonb, 'C', 1, '9c643ee29667', null);
end $$;
