-- Chemistry chapter 12 — 90 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Chemistry' and c.seq = 12
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Chemistry chapter 12: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which chemical is used to detect the presence of water?', '["Sodium chloride","Copper oxide","Anhydrous copper sulphate","Calcium carbonate"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The colour of anhydrous copper sulphate is:', '["Blue","White","Green","Yellow"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'When water is added to anhydrous copper sulphate, it becomes:', '["Red","Black","Blue","Brown"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The melting point of pure water is:', '["100°C","50°C","0°C","–10°C"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The boiling point of pure water is:', '["50°C","80°C","90°C","100°C"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Distilled water is obtained by:', '["Filtration","Sedimentation","Distillation","Evaporation"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Distilled water is commonly used in:', '["Cooking","Car washing","Laboratory experiments","Gardening"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Tap water comes from:', '["Oceans only","Rivers and reservoirs","Factories only","Rain clouds only"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which substance in water is beneficial for aquatic life?', '["Plastics","Sewage","Dissolved oxygen","Oil spills"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Excess nitrates in water mainly come from:', '["Paints","Fertilizers","Wood","Sand"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which pollutant can harm aquatic life seriously?', '["Oxygen","Minerals","Plastics","Salt"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Sewage in water may contain:', '["Vitamins","Harmful microbes","Oxygen","Sugar"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which process removes large suspended particles from water?', '["Chlorination","Sedimentation","Distillation","Evaporation"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Chlorine reacts with water to form:', '["Sulphuric acid","Hydrochloric acid","Hypochlorous acid","Nitric acid"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Typhoid is caused by:', '["Virus","Fungus","Bacteria","Algae"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Hepatitis A mainly spreads through:', '["Clean air","Polluted water","Sunlight","Dust"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Jaundice affects mainly the:', '["Lungs","Liver","Kidneys","Heart"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is a water-borne disease?', '["Dengue","Tuberculosis","Dysentery","Flu"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Water scarcity in Pakistan is increasing due to:', '["Excess forests","Climate change","Low population","Snowfall"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Flood irrigation in Pakistan causes:', '["Water conservation","Water loss","Water purification","More rainfall"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which practice can help reduce water scarcity?', '["Wasting water","Effective water management","Cutting trees","Dumping waste"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is NOT a source of water pollution?', '["Detergents","Sewage","Fertilizers","Pure oxygen"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Dissolved metal compounds in water may:', '["Always be harmful","Provide essential minerals","Remove oxygen","Kill all microbes"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Excess phosphates in water can cause:', '["Better water quality","De-oxygenation","Cooling of water","Distillation"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The process of removing coloured substances from water commonly uses:', '["Charcoal","Iron nails","Chalk","Copper"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which type of water is most suitable for preparing laboratory solutions?', '["River water","Tap water","Distilled water","Sea water"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Water-borne diseases are prevented mainly by:', '["Drinking polluted water","Proper sanitation","Avoiding exercise","Eating more sugar"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following can contaminate groundwater?', '["Septic tanks","Trees","Rocks","Fresh air"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which one is a source of nitrates in water?', '["Fertilizers","Soap","Glass","Sand"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Distillation helps in obtaining:', '["Polluted water","Hard water","Pure water","Coloured water"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which pollutant remains in water for a long time?', '["Sugar","Soap","Detergents","Salt"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Aquatic life depends greatly on:', '["Oil","Dissolved oxygen","Plastic waste","Smoke"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The first step in domestic water treatment is usually:', '["Chlorination","Distillation","Sedimentation","Freezing"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which disease is caused by Salmonella typhi?', '["Cholera","Typhoid","Hepatitis","Dysentery"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Polluted water may contain:', '["Parasites","Bacteria","Viruses","All of these"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which method kills bacteria in water treatment plants?', '["Filtration","Sedimentation","Chlorination","Boiling only"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Excessive extraction of groundwater leads to:', '["Water abundance","Water scarcity","More rainfall","Better rivers"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is an example of household waste?', '["Detergents","Oxygen","Nitrogen","Sand"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The main aim of water purification is to make water:', '["Salty","Colourful","Safe for use","Hot"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Clean drinking water helps prevent:', '["Water-borne diseases","Earthquakes","Floods","Soil erosion"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Responsible water use is important because:', '["Water is unlimited","Water scarcity is increasing","Rainfall never changes","Rivers cannot dry up"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student added fertilizer near a pond. After a few days, fish started dying due to lack of oxygen. Which substance caused this problem?', '["Sodium chloride","Nitrates and phosphates","Sand particles","Oxygen gas"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A laboratory assistant used distilled water instead of tap water while preparing chemicals. What was the main reason?', '["Distilled water is coloured","It contains no dissolved impurities","It boils below 100°C","It contains more oxygen"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During water treatment, large solid particles settled at the bottom of a tank. Which process was taking place?', '["Distillation","Filtration","Sedimentation","Evaporation"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A doctor advised villagers to boil and chlorinate water after flooding. What was the main purpose?', '["To improve taste","To remove microbes","To increase minerals","To cool water"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student observed that white copper sulphate powder turned blue after exposure to a liquid. The liquid was most likely:', '["Oil","Alcohol","Water","Petrol"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A city’s water supply became contaminated with sewage. Which disease is most likely to spread rapidly?', '["Asthma","Cholera","Diabetes","Flu"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Farmers continuously used chemical fertilizers in fields near a river. Which environmental issue may occur first?', '["Increased dissolved oxygen","Water eutrophication","Less algae growth","Reduced pollution"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student heated impure water in a flask and condensed the vapours separately. Which method was used?', '["Filtration","Sedimentation","Distillation","Chlorination"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Villagers dumped household detergents into a stream. Which effect is most likely on aquatic life?', '["Increase in oxygen","Cleaner water","Harm to fish and plants","More drinking water"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A patient developed jaundice after drinking polluted water. Which organ was mainly affected?', '["Heart","Liver","Kidneys","Lungs"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Fish in a polluted lake began dying after sewage disposal. What was the main reason?', '["Increase in dissolved oxygen","Reduction in oxygen level","Increase in rainfall","Presence of distilled water"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'An industrial area released untreated waste into a river. Which type of contamination is most dangerous for humans?', '["Dissolved oxygen","Toxic chemicals","Pure minerals","Sand particles"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A teacher asked students why chlorination is done after filtration. The best answer is:', '["To remove large stones","To kill remaining microorganisms","To increase water level","To add fertilizers"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Excessive groundwater pumping in a city mainly leads to:', '["Water abundance","Lower water table","More rainfall","Increased rivers"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A village used contaminated pond water for drinking. Which precaution would be most effective immediately?', '["Add sugar","Filter and boil water","Store water in sunlight only","Add sand"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During testing, water showed abnormal smell and colour. This suggests the presence of:', '["Pure compounds","Impurities","Distilled vapours","Oxygen only"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A scientist observed rapid algae growth in a lake receiving fertilizers. What phenomenon is occurring?', '["Distillation","Filtration","Eutrophication","Evaporation"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student forgot to chlorinate filtered water before drinking. Which risk increased most?', '["Mineral deficiency","Water-borne diseases","Oxygen reduction","Increased boiling point"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A family started using distilled water for car batteries instead of tap water because distilled water:', '["Contains detergents","Is free from salts","Is cheaper","Contains chlorine"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which situation best indicates water pollution?', '["Clear odourless water","Fish dying suddenly in a pond","Presence of dissolved oxygen","Normal algae growth"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student compared river water with distilled water. Which property is most likely different?', '["Colour of hydrogen","Boiling point","Existence of oxygen atoms","Chemical formula"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A laboratory worker used anhydrous copper sulphate to check moisture in a sample. Why was this chemical suitable?', '["It changes colour in presence of water","It absorbs oxygen only","It releases chlorine gas","It removes impurities"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A polluted river contained excessive phosphates. Which result is most likely?', '["Better fish growth forever","Decrease in aquatic oxygen","Cleaner drinking water","Lower algae growth"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During water purification, activated carbon (charcoal) was added mainly to:', '["Increase microbes","Remove colour and smell","Raise boiling point","Add salts"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A teacher explained that dissolved oxygen is important in rivers because it:', '["Increases pollution","Supports aquatic life","Causes sewage formation","Removes minerals"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which condition best shows poor water management?', '["Drip irrigation","Rainwater harvesting","Flood irrigation wastage","Water recycling"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student accidentally drank contaminated water and developed severe diarrhea. Which disease is most likely?', '["Dysentery","Asthma","Influenza","Migraine"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student noticed that polluted water had an unpleasant odour. Which factor most likely caused it?', '["Pure oxygen","Decomposing organic matter","Distilled salts","Hydrogen gas only"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Why is boiling water effective before drinking?', '["It adds minerals","It kills many harmful microbes","It removes oxygen completely","It increases pollution"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A polluted lake contained plastic waste. Which property of plastics makes them dangerous?', '["They dissolve quickly","They remain in environment for long periods","They increase oxygen rapidly","They evaporate easily"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student compared pure and impure water samples. Which sample would freeze below 0°C?', '["Pure water","Distilled water","Impure water","Boiled water"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which activity contributes most to groundwater contamination?', '["Tree plantation","Leakage from septic tanks","Rainfall collection","Distillation"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a village, children frequently suffered from typhoid. What is the most probable reason?', '["Clean drinking water","Contaminated water supply","Lack of oxygen in air","Excess sunlight"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which observation shows successful chlorination?', '["Large particles settle down","Harmful bacteria are destroyed","Salts are removed completely","Water evaporates quickly"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemist used distilled water in a pH meter. Why?', '["It contains no ions affecting readings","It contains more microbes","It changes colour rapidly","It increases acidity"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which condition is most likely in water with excessive sewage?', '["High oxygen level","Foul smell and microbes","Distilled purity","Absence of bacteria"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A teacher explained that water scarcity can become severe if people continue:', '["Conserving water","Recycling water","Wasting freshwater resources","Building reservoirs"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student used filtration before chlorination because filtration mainly:', '["Removes dissolved salts","Removes suspended impurities","Adds oxygen","Kills all bacteria"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which statement best explains the importance of clean water?', '["It prevents spread of many diseases","It increases water pollution","It reduces rainfall","It causes sewage formation"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student suffered from high fever, weakness, and irregular pulse after consuming unhygienic water from a roadside stall. Which disease is most probable?', '["Dengue","Typhoid","Influenza","Pneumonia"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During a medical camp, doctors found that many patients had yellow skin and eyes due to polluted drinking water. Which organ was mainly affected?', '["Heart","Brain","Liver","Kidneys"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a village, sewage water mixed with drinking water pipelines after heavy rain. Which preventive step would be most effective immediately?', '["Add sugar to water","Chlorinate and boil water","Cool the water","Add detergents"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A child drank contaminated pond water and later developed bloody diarrhea. Which disease is most likely?', '["Dysentery","Asthma","Jaundice","Malaria"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A laboratory test confirmed the presence of Salmonella typhi in a water sample. Which disease can spread through this water?', '["Cholera","Typhoid","Hepatitis A","Dysentery"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'During a flood emergency, health workers distributed chlorine tablets among people. What was the main purpose of these tablets?', '["To improve taste","To kill harmful microorganisms","To increase minerals","To change colour of water"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student frequently consumed contaminated water and developed liver inflammation. Which water-borne disease is most likely responsible?', '["Hepatitis A","Tuberculosis","Asthma","Dengue"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A doctor advised boiling water before drinking during a disease outbreak. Why is boiling effective?', '["It removes all salts","It kills many harmful microbes","It increases oxygen level","It changes colour of water"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A city improved its filtration system but skipped chlorination. Which risk would still remain high?', '["Presence of large particles","Harmful bacteria in water","Mud in water","Suspended sand particles"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A health inspector observed foul-smelling water with sewage contamination in a community. Which statement best explains the danger?', '["It may spread water-borne diseases","It increases dissolved oxygen","It purifies groundwater naturally","It reduces bacterial growth"]'::jsonb, 'A', 1);
end $$;
