-- Chemistry chapter 9 — 64 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Chemistry' and c.seq = 9
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Chemistry chapter 9: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student places water in a sealed flask. After some time, the water level remains unchanged although evaporation continues. This is because:', '["Evaporation has stopped","Condensation has stopped","Evaporation and condensation occur at equal rates","Water molecules stop moving"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A chemist observes that the concentration of reactants and products remain constant for several hours. Which conclusion is correct?', '["The reaction has stopped","The reaction is irreversible","The system has reached equilibrium","All reactants are consumed"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a closed vessel, nitrogen and hydrogen react to form ammonia. Initially, ammonia forms rapidly. After some time, the rate of ammonia formation decreases because:', '["Reverse reaction begins to occur","Catalyst is consumed","Temperature decreases automatically","Pressure becomes zero"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student claims that no reaction occurs at equilibrium because concentrations remain constant. Why is the statement incorrect?', '["Concentrations are not constant","Only reverse reaction occurs","Both forward and reverse reactions continue at equal rates","Products disappear completely"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Hydrated copper(II) sulphate crystals are heated until they become white. This colour change indicates:', '["Formation of copper metal","Removal of water molecules","Addition of oxygen","Formation of a new element"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A white sample of anhydrous copper(II) sulphate turns blue after exposure to moist air. This demonstrates:', '["Dehydration","Oxidation","Reversible hydration","Neutralization"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A pink cobalt(II) chloride sample is heated and becomes blue. The heating process favors:', '["Hydration","Dehydration","Condensation","Dissolution"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A sealed container contains liquid water and water vapour at equilibrium. If some vapour is removed, the system will:', '["Remain unchanged","Produce more vapour through evaporation","Stop evaporating","Freeze immediately"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In an equilibrium system, a student observes millions of molecules reacting every second. This observation supports the concept of:', '["Static equilibrium","Dynamic equilibrium","Irreversible change","Chemical inactivity"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A reaction mixture at equilibrium contains 40% reactants and 60% products. Which statement is correct?', '["Forward rate is greater than reverse rate","Reverse rate is greater than forward rate","Rates of both reactions are equal","Reaction has stopped"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student increases the temperature of an equilibrium system involving dehydration of hydrated copper sulphate. The equilibrium shifts toward:', '["Hydrated salt","Water formation only","Anhydrous salt formation","No change"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Why is a closed system necessary for establishing equilibrium?', '["To prevent catalyst loss","To maintain colour changes","To prevent escape of reactants or products","To increase reaction speed only"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A reaction reaches equilibrium after 30 minutes. After another hour, concentrations remain unchanged. This means:', '["No molecules react anymore","Forward and reverse reactions continue equally","Products have disappeared","Temperature is increasing continuously"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student notices that opening the lid of a bottle containing an equilibrium mixture disturbs the equilibrium because:', '["The system is no longer closed","Temperature becomes zero","Molecules stop moving","Reverse reaction becomes impossible"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A sample of hydrated cobalt chloride is left in a dry environment and gradually turns blue. This happens because:', '["It absorbs water","It loses water molecules","It forms cobalt metal","It reacts with oxygen only"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which observation best indicates equilibrium has been reached?', '["Reactants disappear completely","Product concentration becomes zero","Measurable properties remain constant with time","Colour changes continuously"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a reversible reaction, the forward reaction rate initially decreases because:', '["Product concentration increases","Catalyst is destroyed","Temperature becomes zero","Molecules stop colliding"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student says equilibrium means equal amounts of reactants and products. The correct explanation is:', '["Always true","True only in physical changes","Equilibrium requires equal rates, not necessarily equal amounts","Reactants must be absent"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'When water vapour condenses inside a sealed flask, the process represents:', '["Forward reaction only","Reverse process of evaporation","Decomposition reaction","Neutralization"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The blue colour of hydrated copper sulphate reappears when:', '["Water is added to the white anhydrous salt","The salt is heated strongly","Oxygen is removed","Copper is extracted"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which situation best represents dynamic equilibrium?', '["A stopped pendulum","Water continuously evaporating from an open dish","Liquid water and vapour in a sealed bottle","A burnt matchstick"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a reaction at equilibrium, increasing the concentration of a reactant generally:', '["Disturbs equilibrium","Stops both reactions","Makes the reaction irreversible","Removes products instantly"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A scientist records equal forward and reverse reaction rates. The system must:', '["Be at equilibrium","Have no products present","Be irreversible","Have stopped reacting"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A reversible reaction reaches equilibrium faster when:', '["Molecules collide more effectively","Container is opened","Products are removed continuously","Reactants are absent"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which change clearly demonstrates a reversible reaction?', '["Burning magnesium ribbon","Hydration and dehydration of copper sulphate","Rusting iron","Digestion of food"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student heats hydrated cobalt chloride and observes a colour change. Which evidence suggests equilibrium has shifted?', '["Change in mass only","Change in colour only","Formation of a new element","Explosion occurs"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A student heats blue hydrated copper sulphate repeatedly and then adds water. The colour alternates between blue and white. This demonstrates:', '["Irreversible change","Reversible change","Oxidation only","Reduction only"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A reaction is at equilibrium. Suddenly the forward rate becomes greater than the reverse rate. This means:', '["Equilibrium is disturbed","Equilibrium remains unchanged","Reaction has stopped","Reverse reaction disappeared permanently"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A reaction vessel at equilibrium is shaken thoroughly. Assuming no temperature change, equilibrium:', '["Is permanently destroyed","Remains established","Becomes irreversible","Eliminates products"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The strongest evidence for dynamic equilibrium is that:', '["Reactants disappear completely","Products stop forming","Opposing reactions continue at equal rates","The container becomes empty"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A reaction in which products can reform the original reactants is called:', '["Combination reaction","Irreversible reaction","Reversible reaction","Decomposition reaction"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which symbol is used to represent a reversible reaction?', '["→","←","⇌","="]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In a reversible reaction, the reaction proceeds:', '["Only in forward direction","Only in reverse direction","In both forward and reverse directions","In neither direction"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Chemical equilibrium is achieved when:', '["Reactants are completely consumed","Products stop forming","Forward and reverse reaction rates become equal","Reaction stops completely"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Chemical equilibrium can be established only in:', '["Open system","Closed system","Isolated system only","Any container"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In a closed container, liquid and vapour reach equilibrium when:', '["Evaporation stops","Condensation stops","Evaporation and condensation occur at equal rates","All liquid evaporates"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'At equilibrium, the concentration of reactants and products:', '["Continually increases","Continually decreases","Remains constant","Becomes zero"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which reaction is an example of a reversible reaction?', '["Burning of paper","Rusting of iron","N₂ + 3H₂ ⇌ 2NH₃","Explosion of firecrackers"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The conversion of reactants into products is called:', '["Reverse reaction","Forward reaction","Neutralization","Condensation"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The conversion of products back into reactants is called:', '["Forward reaction","Combination reaction","Reverse reaction","Oxidation reaction"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'At the beginning of a reversible reaction, the reverse reaction rate is often:', '["Maximum","Equal to forward rate","Zero","Constant"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the reaction 2SO₂ + O₂ ⇌ 2SO₃, SO₃ acts as:', '["Reactant in forward reaction","Product in forward reaction","Catalyst","Solvent"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Dynamic equilibrium means:', '["Reaction stops completely","Only forward reaction continues","Both reactions continue at equal rates","Only reverse reaction continues"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which condition is necessary for equilibrium?', '["Constant temperature","Constant concentration","Constant pressure or volume","All of these"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'If temperature changes, equilibrium may:', '["Remain unaffected","Shift to a new position","Stop permanently","Become irreversible"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 1, 'When hydrated copper(II) sulphate is heated, its colour changes from:', '["White to blue","Pink to blue","Blue to white","Blue to pink"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Hydrated copper(II) sulphate is:', '["White solid","Blue solid","Pink solid","Green solid"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Anhydrous copper(II) sulphate is:', '["Blue solid","Green solid","White solid","Pink solid"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Adding water to anhydrous copper(II) sulphate causes it to become:', '["Black","White","Green","Blue"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Heating hydrated copper(II) sulphate removes:', '["Sulphur dioxide","Oxygen","Water of crystallization","Copper ions"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Hydrated cobalt(II) chloride is:', '["Blue solid","Pink solid","White solid","Yellow solid"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Anhydrous cobalt(II) chloride is:', '["Pink solid","Blue solid","Green solid","White solid"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 1, 'When hydrated cobalt(II) chloride is heated, it:', '["Turns pink","Turns blue","Turns green","Melts"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Adding water to anhydrous cobalt(II) chloride shifts equilibrium:', '["To the right","To the left","Upward","Downward"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which reaction is favored when temperature increases?', '["Exothermic reaction","Endothermic reaction","Neutralization reaction","Combustion reaction"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'At equilibrium, the amount of reactants:', '["Continuously decreases","Continuously increases","Remains constant","Becomes zero"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which statement is true at equilibrium?', '["No molecules react","Only products are present","Reaction rates are equal","Reactants disappear completely"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A reaction that goes to completion is called:', '["Reversible reaction","Equilibrium reaction","Irreversible reaction","Dynamic reaction"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Equilibrium can be achieved when:', '["Only reactants are placed in a closed container","Only products are placed in a closed container","Reactants and products are placed together","Any of these situations"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which process occurs simultaneously in a reversible reaction?', '["Melting and freezing","Forward and reverse reactions","Oxidation only","Reduction only"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Sulphur trioxide can decompose into:', '["SO₂ and O₂","S and O₂","SO₂ only","SO₄ only"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which of the following is NOT true for equilibrium?', '["Forward rate equals reverse rate","Concentrations remain constant","Reaction stops completely","Dynamic condition exists"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'If the evaporation rate becomes equal to the condensation rate, the system is:', '["Melting","Boiling","At equilibrium","Freezing"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Equilibrium is established in an irreversible reaction:', '["Quickly","Slowly","Never","At high temperature only"]'::jsonb, 'C', 1);
end $$;
