-- Computer Science chapter 2 — 29 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Computer Science' and c.seq = 2
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Computer Science chapter 2: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, '"How to stop infectious diseases?" is a real-world problem belonging to which field?', '["Economic","Education","Healthcare","Transportation"]'::jsonb, 'C', 1, 'ea67e091a96d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In computer science, a "computing problem" is specifically defined as a problem that is solved:', '["Only by using the internet.","Step-by-step using computation.","By a human without a machine.","Instantly without any steps."]'::jsonb, 'B', 1, 'b6ebf2f1e811', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When checking if a specific number is "Prime" or "Not Prime," you are dealing with which type of computing problem?', '["Search Problem","Decision Problem","Counting Problem","Abstraction Problem"]'::jsonb, 'B', 1, '96096c3b8af4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a "Search Problem," which element represents the specific moves that transition from one node to another?', '["Initial State","Operations","Goal","Decision Diamond"]'::jsonb, 'B', 1, '83ee2a1a3a18', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To solve a search problem, the "target of end condition" is officially known as the:', '["Initial State","Operation","Goal","Start State"]'::jsonb, 'C', 1, 'd4a2b2584fb5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If you have 5 shirts and 3 pants, how many "total possible casual dresses" can you form?', '["8","15","53","2"]'::jsonb, 'B', 1, '907854a4f508', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If you enter your home and see water on the floor, what do you need to solve such problems?', '["High-speed internet access","Reasoning skills that are based on evidence and facts","A calculator to measure the volume of water","Advanced programming knowledge"]'::jsonb, 'B', 1, '94698707a7fb', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the I-P-O model, which term refers specifically to the "requirements from the environment"?', '["Input","Process","Output","Storage"]'::jsonb, 'A', 1, '2413290c5283', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'For a programmer, an I-P-O chart is considered to be a:', '["Type of hardware.","Handy tool to solve problems.","Decision problem.","Form of machine code."]'::jsonb, 'B', 1, 'e830e7817871', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In an I-P-O chart, the "Process" column is defined as:', '["Data entered into the system.","Operations that will be applied on the input.","Data that has been turned into information.","The hardware used for the computation."]'::jsonb, 'B', 1, '5ca50be570d3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If you are calculating the "Average of 5 numbers," the division operation would be listed in which section of the I-P-O chart?', '["Input","Process","Output","Storage"]'::jsonb, 'B', 1, '0a93406a8113', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the official definition of "Output" in the I-P-O tabular form?', '["Requirements from the environment.","Operations applied to the data.","Data that has been turned into the Information.","The physical screen of the computer."]'::jsonb, 'C', 1, '3fc4bb1df16a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '"Computational Thinking" is often described as an extension of which type of thinking?', '["Mathematical Thinking","Logical Thinking","Creative Thinking","Fast Thinking"]'::jsonb, 'B', 1, '4a34a661f0f8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which property of computational thinking involves "removing the unnecessary details" to focus on essential info?', '["Decomposition","Abstraction","Pattern Recognition","Algorithm Design"]'::jsonb, 'B', 1, '2154b9cc6348', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The process of "examining a problem for similarities between previously solved problems" is:', '["Decomposition","Abstraction","Pattern Recognition","Algorithm Design"]'::jsonb, 'C', 1, '08deafeecf82', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '"Actual designing of solution" and "creating step-by-step plan" defines:', '["Logical Thinking","Algorithm Design","I-P-O Modeling","Problem Analysis"]'::jsonb, 'B', 1, '01b07ff23561', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the "Video Game" example, ignoring the "weather" while focusing on the "exit" is an example of:', '["Decomposition","Abstraction","Logical Thinking","Input Identification"]'::jsonb, 'B', 1, '1d8b311efd3b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Treating "Six enemies as a single enemy" because they behave the same way is an example of:', '["Decomposition","Abstraction","Pattern Recognition","Search Problem"]'::jsonb, 'C', 1, '2bbbe25d86e1', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the benefit of developing "algorithmic thinking skills"?', '["You become a hardware engineer.","You become a better problem solver.","You can type 100 words per minute.","You no longer need a computer."]'::jsonb, 'B', 1, 'b0a2a54a90b6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which solution design method is described as a "diagrammatic representation of an algorithm"?', '["Flowchart","Concept Map","I-P-O Model","Machine Code"]'::jsonb, 'A', 1, 'ffea117729c8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Every flowchart should officially start with a "trigger," which is represented by which shape?', '["Rectangle","Parallelogram","Oval shape","Diamond"]'::jsonb, 'C', 1, '31f437682094', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which graphical shape represents the "Input to the flowchart"?', '["Oval","Parallelogram","Rectangle","Diamond"]'::jsonb, 'B', 1, 'ed3e0e3de813', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a formula (like Area = (Base x Height) / 2) is applied in a flowchart, which symbol is used?', '["Oval","Parallelogram","Rectangle","Diamond"]'::jsonb, 'C', 1, 'c94321290c74', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a flowchart needs to check a condition (like "Is Grade > 50?"), which symbol is used?', '["Rectangle","Diamond","Oval","Circle"]'::jsonb, 'B', 1, '866054ffbf6f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why might a flowchart have "multiple ends"?', '["Because the programmer got confused.","Because of the possibility of multiple decision points.","Because it is a complex search problem.","Because the trigger was not an oval."]'::jsonb, 'B', 1, '2b365294da45', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which software tool is mentioned as famous for drawing various types of diagrams, including flowcharts?', '["LARP","Microsoft Visio","Canva","ChatGPT"]'::jsonb, 'B', 1, '0c1a8e3526ea', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The LARP programming language is unique because it uses:', '["Only binary code (0s and 1s).","Semi-natural syntax.","Only graphical icons.","Complex machine language."]'::jsonb, 'B', 1, 'd8c5a8f28c14', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the "Video Game Development" concept map, what are the three sub-concepts under "Game Design"?', '["Gameplay Mechanics, Level Design, and Storyline.","Coding, Scripting, and Engines.","2D Art, 3D Models, and Animation.","Sound Effects, Music, and Voice Acting."]'::jsonb, 'A', 1, '9ab87a462558', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following methods are mentioned for designing a solution?', '["Flowcharts and Source Code","Concept Maps and Pseudo-code","Flowcharts and Concept Maps","Algorithms and Charts"]'::jsonb, 'C', 1, '5a2f8a7b58cb', null);
end $$;
