-- Computer Science chapter 7 — 28 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Computer Science' and c.seq = 7
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Computer Science chapter 7: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a goal is "precise and clear in setting up," it follows which part of the SMART framework?', '["Measurable","Specific","Realistic","Achievable"]'::jsonb, 'B', 1, '58939f1bdabc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A goal that is "quantifiable and can be assessed" is known as:', '["Specific","Measurable","Time-Bound","Realistic"]'::jsonb, 'B', 1, '06e7263a42c0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '"Set attainable small goals which can be achieved" is the definition of which SMART category?', '["Specific","Achievable","Realistic","Time-Bound"]'::jsonb, 'B', 1, 'f24b4e9e0f89', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a business plan, goals that are "convincing in nature, not in the clouds" are:', '["Specific","Realistic","Time-Bound","Achievable"]'::jsonb, 'B', 1, '44730bdff8b5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why do SMART goals need to be "Time-Bound"?', '["To ensure the founder works 24 hours a day.","Because strategies and goals need to be reviewed for improvement.","To close the business as soon as possible.","To make the goal sound more professional to banks."]'::jsonb, 'B', 1, '7b0a56380a7c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If "demand is great for the available supply," what is the logical action for profit?', '["The price should be decreased immediately.","The price (and thus the profit) may be increased.","The business should stop selling the item.","The markup should be removed."]'::jsonb, 'B', 1, '1398b64a5a4a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is a recognized "Drawback" of entrepreneurship?', '["Having the power to gain control over one''s own life.","Uncertainty of income and the risk of losing their investments.","The ability to make a difference in the world.","Becoming self-fulfilled through their professional work."]'::jsonb, 'B', 1, 'd0644ed51b11', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'How is the "Design Thinking" process officially described?', '["It is a simple, straight line where you never repeat a previous step.","It is an iterative and non-linear process that contains five phases.","It is a secret method that only professional artists are allowed to use.","It is a mathematical formula used only to find the cost of goods."]'::jsonb, 'B', 1, '7947dcec2c46', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'During the "Empathize" phase, what is the main objective?', '["Understand the user thoroughly within the context of your design challenge.","Pick the first idea you have and start selling it to the public immediately.","Calculate the total amount of money you need to borrow from a bank.","Design a very colorful logo using a digital tool like Canva."]'::jsonb, 'A', 1, 'b0feaff69793', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the goal of the "Define" phase in problem-solving?', '["Brainstorm as many different ideas as you can in one hour.","Identify the right problem and create an actionable problem statement.","Build a very expensive and high-quality final version of your product.","Hire a team of experts to tell you what your users are thinking."]'::jsonb, 'B', 1, '790a0ffc7d29', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the "Ideate" phase, entrepreneurs are encouraged to:', '["Narrow down their options to only one single solution as fast as possible.","Come up with as many ideas as possible to solve the problem statement.","Stop thinking of new ideas once they find one that is very cheap.","Focus only on the ideas that their competitors are already using."]'::jsonb, 'B', 1, '93fb91b72f80', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the strategic purpose of building a "Prototype"?', '["To show the world that your business is already very successful and rich.","To build a sample model to learn fast, learn cheap and learn early.","To replace the need for ever talking to real customers in the future.","To create the final, permanent version of the product for the market."]'::jsonb, 'B', 1, '86a5b8ae15e9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why is the "Test" phase so important for the final solution?', '["To collect feedback from users to refine the problem, solution and user needs.","To prove to the users that your first idea was already perfect.","To find out which of your employees is working the hardest.","To calculate the exact markup percentage for your new service."]'::jsonb, 'A', 1, 'fc7701477d27', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following shows the correct sequence of the five phases of Design Thinking?', '["Define, Ideate, Empathize, Test, Prototype","Empathize, Define, Ideate, Prototype, Test","Ideate, Empathize, Prototype, Test, Define","Prototype, Test, Empathize, Define, Ideate"]'::jsonb, 'B', 1, 'cb53acadaaa7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To find a realistic final Selling Price, what three things must an entrepreneur add together?', '["Cost of Production + Overheads + Profit","Cost of Production + Competitor''s Price + Profit","Overheads + Salary + Marketing Price","Only Cost of Production + Profit"]'::jsonb, 'A', 1, '0b87d421ca81', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A SWOT analysis is used to evaluate a product by examining which four core elements?', '["Salary, Overheads, Production, and Profit","Advantages, Disadvantages, Possibilities, and Risks","Software, Templates, Workbooks, and Technology","Strategy, Supply, Sales, and Structure"]'::jsonb, 'B', 1, 'afaf071662d3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Questions regarding the shape, size, and color of a product help a business understand why customers:', '["Are willing to pay a commercial price","Need a specific hour of service","Like or dislike the product","Are classified by income status"]'::jsonb, 'C', 1, '04e80d289c4b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If customers decide to stop buying a product completely, the market demand is considered:', '["Sustainable","Unsustainable","Commercial","Regular"]'::jsonb, 'B', 1, '6fc15ebab3e9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the main difference between "Demand" and "Customers"?', '["Customers only need the product, but demand does not.","Customers are willing to pay for the product, while demand is just the need.","Demand represents the businesses, while customers represent the community.","There is no difference between them."]'::jsonb, 'B', 1, '8d017e9c6ca5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If two different shopkeepers are selling similar items in the same market, they are called:', '["Partners","Competitors","Customers","Surveyors"]'::jsonb, 'B', 1, '014bab6d6bc8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A business is considered "Sustainable" if the customers buy the product:', '["Only one time.","Regularly or seasonally.","Never again.","Only when the price drops to zero."]'::jsonb, 'B', 1, 'fb8bc0df3fae', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is defined as a free-to-use, online versatile app that lets users create stunning graphics, videos, and social media content?', '["LivePlan","WordPress","Canva","Business PlanWriter"]'::jsonb, 'C', 1, '39f9aabcdc6b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'WordPress serves globally as an open-source tool specifically designed for:', '["Operating System (OS)","Content Management System (CMS)","Database Management System (DBMS)","Graphic Design Suite"]'::jsonb, 'B', 1, '92e6302568ce', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which entrepreneurial skill involves working with others and accepting individuals irrespective of their caste, gender, social status, or disability?', '["Conducting myself","Interacting with people","Thinking","My safety and survival"]'::jsonb, 'B', 1, '1237fef5ee94', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which comprehensive business planning software is purposefully designed to give you all the tools you need to create your business plan and present it?', '["LivePlan","WordPress","Canva","Business PlanWriter"]'::jsonb, 'A', 1, 'c19eb9e09c9a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which specialized business planning application is a dedicated spreadsheet program that is a part of the SoftMaker Office suite?', '["LivePlan","PlanWrite","PlanMaker","WordPress"]'::jsonb, 'C', 1, 'b2687524ed63', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which business planning software listed in the text is developed by Palo Alto Software?', '["PlanMaker","Business Plan Pro","PlanWrite","WordPress"]'::jsonb, 'B', 1, '7f4d60ef9201', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following terms describes a person who starts, organizes, and manages a business while taking on financial risks for the sake of profit?', '["Manager","Investor","Entrepreneur","Employee"]'::jsonb, 'C', 1, '57067c905e54', null);
end $$;
