-- Computer Science chapter 1 — 30 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Computer Science' and c.seq = 1
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Computer Science chapter 1: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The "Pascaline" (1642) performed basic arithmetic using which specific mechanism?', '["Vacuum tubes","Punched cards","Gears and wheels","Transistors"]'::jsonb, 'C', 1, 'e5fb1f06ea80', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which component is described as the "backbone" of the computer that enables communication between all hardware parts?', '["The Central Processing Unit","The Motherboard","The Hard Disk Drive","The Power Supply Unit"]'::jsonb, 'B', 1, '2fa7a1a44ec3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which generation introduced the standard use of keyboards and monitors?', '["Second Generation","Third Generation","Fourth Generation","Fifth Generation"]'::jsonb, 'B', 1, 'f4d1e230a000', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, '"Self-regulation and stability" are the defining characteristics of which system type?', '["Natural Systems","Artificial Systems","Operating Systems","Network Systems"]'::jsonb, 'A', 1, '51e5e643b4d8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which input device is specifically used to convert "sound into digital signals"?', '["Scanner","Microphone","Barcode Reader","Digital Camera"]'::jsonb, 'B', 1, '3d6e04d9149f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In the microprocessor, if the system needs to compare two numbers to see which is larger, which unit handles this task?', '["Control Unit (CU)","Arithmetic Logic Unit (ALU)","L3 Cache","Memory Address Register"]'::jsonb, 'B', 1, '69df98dc6e7a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In Von Neumann Architecture, where are "instructions and program data" stored according to the core concept?', '["In separate physical devices","Together in the same memory","Only in the Accumulator register","Directly on the Control Bus"]'::jsonb, 'B', 1, '52b0e94be0bf', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'What is the specific role of the "Program Counter (PC)" register during the instruction cycle?', '["It holds the result of a mathematical addition","It contains the memory address of the next instruction to be executed","It decodes the current instruction into binary code","It manages the flow of data to the printer"]'::jsonb, 'B', 1, '84b9ecc74c88', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 1, 'If a CPU needs to move data but NOT the memory address, which pathway is utilized?', '["Address Bus","Data Bus","Control Bus","Expansion Slot"]'::jsonb, 'B', 1, 'f228a39e7d87', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Within the microprocessor, which unit manages and directs all system activities during instruction execution?', '["Arithmetic Logic Unit (ALU)","Control Unit (CU)","Registers","Cache"]'::jsonb, 'B', 1, '2aae0a625e94', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'What distinguishes "Firmware" from standard application software?', '["It is easily deleted by the user","It is permanently stored on hardware devices","It is used only for word processing","It requires a browser to execute tasks"]'::jsonb, 'B', 1, 'fd52f664c16b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In data communication, what is the role of the "Protocol"?', '["To provide the physical path for the message","To act as a set of rules that governs data communications","To convert electrical signals into light","To increase the speed of the sender"]'::jsonb, 'B', 1, '73a7a9bb4888', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which communication mode is compared to a "two-way street" where traffic flows in both directions at the same time?', '["Simplex mode","Half-duplex mode","Full-duplex mode","Asynchronous mode"]'::jsonb, 'C', 1, 'bae2849e17f4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A network that spans an entire city, covering an area between "5 to 50 km", is officially a:', '["LAN","WAN","MAN","VPN"]'::jsonb, 'C', 1, '29914c9d5535', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which category of application software includes tools like "Microsoft Word" and "Google Sheets"?', '["Business Software","Productivity Software","Entertainment Software","Educational Software"]'::jsonb, 'B', 1, 'be5b1e5afbfb', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, '"LMS" (Learning Management Systems) are categorized as which type of software?', '["Productivity","Business","Educational Software","System Utility"]'::jsonb, 'C', 1, 'ecb8093c33b6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, '"Mnemonics" like MOV and ADD are the symbolic codes used in which language?', '["Machine Language","Assembly Language","High Level Language","Java"]'::jsonb, 'B', 1, 'f1a21467dda5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'In a "Star Topology", what is the consequence if the central hub or switch fails?', '["Only one computer stops working","The whole network goes down","Data starts traveling in a circle","The network automatically switches to Bus topology"]'::jsonb, 'B', 1, 'fd1b8b91a26a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which Internet technology allows data packets to potentially take "different routes" to reach their destination?', '["Circuit Switching","Packet Switching","Simplex Transmission","Synchronous Timing"]'::jsonb, 'B', 1, '0605bfc94df0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'What is listed as a significant "Disadvantage" of the Internet regarding human social behavior?', '["Global Connectivity","Digital Addiction and social isolation","Real-time communication","Enhanced productivity"]'::jsonb, 'B', 1, '8398e40a2a0d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, '"Walkie-talkies" are the classic example of which communication mode?', '["Simplex","Half-duplex","Full-duplex","Synchronous"]'::jsonb, 'B', 1, 'fee098648760', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which transmission type uses "Start and Stop bits" because character timing is variable?', '["Synchronous","Asynchronous","Parallel","Full-duplex"]'::jsonb, 'B', 1, 'babd37b1d11a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'When you are "reading a web page" on your browser, which protocol is working behind the scenes?', '["FTP","HTTP","SMTP","TCP"]'::jsonb, 'B', 1, '465fe2f33d87', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'FORTRAN and ALGOL are classic examples of which high-level language category?', '["Procedural Languages","Structured Languages","Object-Oriented Languages","Machine Languages"]'::jsonb, 'A', 1, 'a2000dbe7bec', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Data transmission from a computer to a printer, or broadcasting via radio and television, takes place in which mode?', '["Simplex mode","Half-duplex mode","Full-duplex mode","Asynchronous mode"]'::jsonb, 'A', 1, 'e49832568705', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Without which of the following component can two devices be physically connected but still unable to communicate or exchange information?', '["Receiver","Medium","Protocol","Notice board"]'::jsonb, 'C', 1, '839767435dcf', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which layer of the OSI model is explicitly responsible for converting data into a format that ensures compatibility across different systems?', '["Application Layer","Presentation Layer","Session Layer","Transport Layer"]'::jsonb, 'B', 1, '2131fe056c5d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'Which OSI layer determines the optimal path for data transmission using devices like routers?', '["Physical Layer","Data Link Layer","Network Layer","Application Layer"]'::jsonb, 'C', 1, '36e02da27a53', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'The modern global Internet originally evolved from a 1960s research project designed for military installations and research institutions. What was the name of this project?', '["World Wide Web","Internet of Things","ARPANET","ISP Web"]'::jsonb, 'C', 1, 'da495baaea34', null),
    (v_chapter, 'mcq', 'concept', 'bank', 1, 'A network setup that is typically smaller and usually consists of "between two and ten computers" is called:', '["Client/Server Network","Peer-to-Peer Network","Dedicated Server Network","Central Switch Network"]'::jsonb, 'B', 1, '22217c1a3968', null);
end $$;
