-- Computer Science chapter 3 — 31 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Computer Science' and c.seq = 3
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Computer Science chapter 3: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a professional development team, the person responsible for creating the "Graphical User Interface (GUI)" is known as the:', '["Front-end Developer.","Back-end Developer.","Database Administrator.","Network Engineer."]'::jsonb, 'A', 1, 'ceeb731be0a6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the functional difference between the starting tag <tag> and the ending tag in HTML?', '["The ending tag uses a backslash \\.","The ending tag is recognized with the help of a forward slash /.","The starting tag must be in capital letters.","There is no difference between them."]'::jsonb, 'B', 1, '11cc209fe7dc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the official file extension required for a browser to recognize a document as an HTML file?', '["txt","doc","html","web"]'::jsonb, 'C', 1, 'd7df62092739', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Where must all the "main constituents" of an HTML document be arranged?', '["Inside the <head> tag-pair.","Inside the <body> tag-pair.","Before the <html> tag.","Inside the title section."]'::jsonb, 'B', 1, 'aabcec745b8d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the functional difference between <span> and <div> in text arrangement?', '["Span provides style to a single line; Div provides it to a set of lines.","Div is for images; Span is for text.","Span is for the header; Div is for the footer.","There is no difference; they are interchangeable."]'::jsonb, 'A', 1, 'd87d359daf14', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which tag-pair should be used if you want to emphasize a word specifically with "italics" as a note?', '["<b>","<i>","<u>","<sub>"]'::jsonb, 'B', 1, 'd5b40853782a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the text "Strong character," which tag-pair is officially used for the display of "bold and strong characters"?', '["<em>","<small>","<strong>","<sup>"]'::jsonb, 'C', 1, '9c19f3ba9beb', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a developer wants a heading that is "largest and most important," which level should they choose?', '["Level 1 (h1)","Level 6 (h6)","Level 10 (h10)","Main Level (h0)"]'::jsonb, 'A', 1, '6ae4f225a851', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'According to the DOM tree hierarchy, what does the ''html'' node contain?', '["Only the images of the site.","Two sub-nodes: ''head'' and ''body''.","The web browser''s search engine index.","The password for the CRM system."]'::jsonb, 'B', 1, '04f98ec8dc9f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which IDE environment is mentioned as being used for the "Visual Studio version 2022" examples in the text?', '["Netbeans","Microsoft Visual Studio","Notepad","Canva"]'::jsonb, 'B', 1, 'bce11bf072e6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'How many languages can the Microsoft Visual Studio IDE support for writing and running code?', '["Only 1 (HTML)","Exactly 10","More than 30","Exactly 100"]'::jsonb, 'C', 1, '1bd2bd3ac259', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A developer wants to organize data using bullets of type "circle" or "square." Which tag-pair must be used as the parent container?', '["<ul>","<ol>","<li>","<dl>"]'::jsonb, 'A', 1, 'c5b4c62df7e4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a professional HTML table, which tag-pair is specifically designated to allocate and designate data within a "Header Row"?', '["<td>","<tr>","<th>","<table>"]'::jsonb, 'C', 1, '1208441745d7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why is JavaScript considered an ideal language for making webpages dynamic at the "client-end"?', '["It requires a very high amount of memory to run.","It does not consume much memory and works on any operating system.","It can only be used on Windows-based servers.","It replaces the need for using any HTML tags."]'::jsonb, 'B', 1, 'b1cef23c52bf', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'In programming, what is the official term for a user action that can be "sensed" and triggers a specific task to be done?', '["Script","event","Variable","Function"]'::jsonb, 'B', 1, '1ea7ca75fd1d', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'Which JavaScript function is used to display a notification or message box to inform the user about the result of an action?', '["alert()","prompt()","document.write()","console.log()"]'::jsonb, 'A', 1, '9df2d00f8f00', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'Which JavaScript function allows the program to take input from the user via a message window?', '["alert()","prompt()","document.write()","var()"]'::jsonb, 'B', 1, '2671e796dd00', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which JavaScript operator is used when you specifically need the "remainder" of a division operation?', '["/ (Division)","% (Modulus)","* (Multiplication)","+ (Addition)"]'::jsonb, 'B', 1, 'f5b0d4d85c86', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the purpose of the comparison operator != in a selection statement?', '["To check if two values are equal.","To check if two values are not equal.","To check if the left value is greater.","To check if the right value is smaller."]'::jsonb, 'B', 1, '2f9384795560', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a selection scenario where there are "more than two possibilities," which structure should be used to extend the logic?', '["if statement","if-else statement","if-else if-else statement","For Loop"]'::jsonb, 'C', 1, 'e2ec97318633', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the primary advantage of using an "Iterative Statement" like a For Loop?', '["It makes the code more difficult to read.","The same task is achieved in much lesser lines of code.","It prevents the computer from using any memory.","It only works for mathematical calculations."]'::jsonb, 'B', 1, 'c427b9f3addf', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a For Loop, which three components must be set to control the number of iterations?', '["Start, Stop, and Pause.","Initialization, terminating condition, and step-size.","HTML, CSS, and JS.","Input, Process, and Output."]'::jsonb, 'B', 1, '92daad3080e4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the starting "index number" for any array declared in JavaScript?', '["0","1","-1","10"]'::jsonb, 'A', 1, '6b4ea19770f2', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'Which debugging command allows a programmer to trace the code "line by line"?', '["Start Debugging","Step Into","Toggle Breakpoint","Restart"]'::jsonb, 'B', 1, '8fe815b96935', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'When a programmer wants to add a note in the code that is "not part of the output" and is "ignored by the browser," they use:', '["Tags","comments","Breakpoints","Alerts"]'::jsonb, 'B', 1, 'fa2b5a7d4dee', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'According to the DOM tree hierarchy, which node is located at the "absolute top" for a whole webpage?', '["Document","html","head","body"]'::jsonb, 'A', 1, '8e2ef90c7ce4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is the correct order of priority of CSS styles if all three are used in a webpage?', '["External CSS → Embedded CSS → Inline CSS","Embedded CSS → External CSS → Inline CSS","Inline CSS → Embedded CSS → External CSS","Embedded CSS → Inline CSS → External CSS"]'::jsonb, 'C', 1, 'b36624a0a819', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which CSS method is recommended for large projects?', '["Inline CSS","Embedded CSS","External CSS","Internal CSS"]'::jsonb, 'C', 1, '4590852e9a1e', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a user is unable to recall the specific URL of a webpage, which tool creates "different combinations" based on keywords to locate it?', '["Web Browser","Search Engine","Web Hosting Service","Hyper-Text Markup Language"]'::jsonb, 'B', 1, '8223062f0c3c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the first step to establishing a digital presence?', '["Website Development","Visual Studio Installation","Writing JavaScript","Buying a Web Server"]'::jsonb, 'A', 1, '5586a71641b4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is a website called if the information is changed or adjusted in accordance with user input or choice?', '["Static Website","Dynamic Website","Single Page Website","Offline Website"]'::jsonb, 'B', 1, '0591086b011d', null);
end $$;
