-- Computer Science chapter 6 — 30 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Computer Science' and c.seq = 6
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Computer Science chapter 6: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When creating a "strong and unique password," what specific mix is recommended?', '["Capital and lowercase letters, numbers, and special characters.","Only your name followed by your birth year.","Just a long list of numbers that are easy to remember.","The name of your favorite sports team and city."]'::jsonb, 'A', 1, '785dbbbb0d74', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why is it important to backup data in a "safe place" like an external drive or the cloud?', '["To make sure other people can see your files easily.","To ensure you would not lose your important data if your computer gets stolen or damaged.","To clear space on the computer so it can play games faster.","To follow government rules about internet usage."]'::jsonb, 'B', 1, '0c2562ae26e1', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the specific misleading technique used by scammers during a phishing attack?', '["Using a program to slow down your internet speed.","Scammers pretend to be official and try to trick you.","Physically stealing the external hard drive from your home.","Sending unsolicited and irrelevant messages via email."]'::jsonb, 'B', 1, '8ffb37e3ce57', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Public Wi-Fi networks are generally avoided for private tasks because they are:', '["Too expensive to use for long periods.","More susceptible to hackers.","Not allowed to open banking websites.","Only available in large city centers."]'::jsonb, 'B', 1, '8f5dd53998ab', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To ensure the safety of your system from malware, what is the rule for downloading files?', '["Download apps, programs, and files only from reliable websites.","Download only from websites that do not require any login details.","Open every attachment in emails to check for potential updates.","Only download files when your antivirus software is turned off."]'::jsonb, 'A', 1, 'ecfc288f066f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Regarding physical security, what action should you take for your workspace?', '["Keep your computer screen visible to everyone in the room.","Lock your computer when you are away from it.","Avoid using any passwords for your social media accounts.","Share your home address on all digital platforms for verification."]'::jsonb, 'B', 1, '893b9a5c4bef', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'Ethical use of software requires a user to avoid:', '["Updating the software to the latest version.","Malicious purposes, such as hacking, spreading malware, or cyberbullying.","Using software for educational or business tasks.","Changing the privacy settings of the software."]'::jsonb, 'B', 1, '658fc18bd89d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '"Protection of Individual Rights" in the digital age means:', '["Everyone has the right to use any software for free.","Safeguarding a person''s personal information, freedom, and privacy.","Preventing the government from ever seeing your online activities.","Allowing people to copy anyone’s work without permission."]'::jsonb, 'B', 1, '481d1c8a88a6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What mental health conditions are associated with the "harmful effect" of digital addiction?', '["Anxiety, depression, and social isolation.","Increased focus and better memory.","Improved social skills and physical health.","A better understanding of computer hardware."]'::jsonb, 'A', 1, 'da09176ad37f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which general term describes any software that is specifically created with the intent to harm, exploit, or disrupt a computer network?', '["Phishing","Malware","Hacking","Cookies"]'::jsonb, 'B', 1, '1d9de384f885', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a cybercriminal uses fake emails or websites to trick individuals into revealing sensitive information, what is this specific deceptive method called?', '["Malware","Phishing","Hacking","Pharming"]'::jsonb, 'B', 1, '9d7780cd75f7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the term used for unsolicited, irrelevant, or inappropriate messages sent over the internet?', '["Spyware","Pharming","Spam","Hacking"]'::jsonb, 'C', 1, '7763f2723f1a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What specific tool should be used to encrypt a connection if necessary when using public Wi-Fi?', '["Browser cookies","Virtual private network (VPN)","Antivirus program","Public hotspot"]'::jsonb, 'B', 1, 'dd3785d0b0ba', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A software tracking your online activities and sending the data to advertisers without your knowledge or consent is called:', '["Spam","Phishing","Spyware","Pharming"]'::jsonb, 'C', 1, '94f4093ee0f9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a computer system or network faces unauthorized access or manipulation, it is called:', '["Hacking","Phishing","Malware","Spyware"]'::jsonb, 'A', 1, '1d0be467016c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a person is targeted by deceptive schemes that are explicitly designed to trick people for financial gain or personal information, what is it called?', '["Cookies","Scam","Pharming","Software Piracy"]'::jsonb, 'B', 1, 'cbc251c2a776', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If someone engages in the unauthorized copying, distribution, or use of software without proper licensing, which term defines this act?', '["Freeware","Shareware","Software Piracy","Cookies"]'::jsonb, 'C', 1, 'b8ca7e6b9a0e', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'What term describes the small text files stored on a user''s device, containing information about their interactions with a website?', '["Shareware","Scam","Freeware","Cookies"]'::jsonb, 'D', 1, '0b3d1f5a5f85', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'What specific threat is carried out by redirecting website traffic to a fake site without the user''s knowledge?', '["Cookies","Scam","Shareware","Pharming"]'::jsonb, 'D', 1, '263ba3aec0fd', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a user downloads Mozilla Firefox, which is a free web browser, what type of software are they using?', '["Shareware","Freeware","Software Piracy","Scam"]'::jsonb, 'B', 1, '00e92fd9daaf', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If an organization adopts the Linux operating system because its source code can be openly viewed, modified, and distributed by anyone, what type of software are they utilizing?', '["Shareware","Open Source","Freeware","Tradeoff"]'::jsonb, 'B', 1, '5119b43eb168', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Using complex passwords or encryption to protect your data is a practical example of:', '["Information Privacy","System Security","Tradeoff","Access Control"]'::jsonb, 'A', 1, '4625697f8312', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Firewalls, encryption, antivirus software, and access control are all classified as core examples of:', '["Information Privacy","System Security","Open Source","Tradeoffs"]'::jsonb, 'B', 1, 'd5a0b78e579d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Online platforms like Facebook, WhatsApp, and Instagram are explicitly designed to facilitate the exchange of:', '["Fake news and disinformation","Deceptive schemes and updates","Ideas, interests, and personal updates","Public discourse and restrictions"]'::jsonb, 'C', 1, '6961fc080960', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The Apple logo on iPhones and MacBooks is a direct, practical example of which legal tool?', '["Patent","Copyright","Trademark","Disinformation"]'::jsonb, 'C', 1, 'd7f67dd1417b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When an author writes a book and automatically holds the legal right that prevents others from reproducing or distributing the work without permission, they are exercising a:', '["Patent","Copyright","Trademark","Tradeoff"]'::jsonb, 'B', 1, 'dacbf1980445', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Ensuring that no one can copy or use someone else''s work (such as books, music, or software) without permission is the primary function of:', '["Protection of Individual Rights","Intellectual Property Ownership","Prevention of Unauthorized Use","Software Copyright"]'::jsonb, 'B', 1, '52ab387e749f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'While social media and messaging apps make communication fast and easy, which tools specifically simplify finding information?', '["Secure digital payments","Search engines like Google","Automation and technology","Software development"]'::jsonb, 'B', 1, 'b004fd446c4f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which specific issue is facilitated by social media platforms when individuals are harassed, threatened, or humiliated online?', '["Security breach","Cyberbullying","Disinformation","Tradeoff"]'::jsonb, 'B', 1, 'f7e2bc5930f3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Fake news on social networking platforms specifically refers to false or misleading information that is presented as:', '["Conspiracy theories","Factual news","Security breaches","Analytical data"]'::jsonb, 'B', 1, 'de967cbb8cf8', null);
end $$;
