-- Maths chapter 2 — 57 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Maths' and c.seq = 2
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Maths chapter 2: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, '0.0009988 × 10¹⁰ in standard notation is:', '["9,988,000","998,800","99,880,000","9,988"]'::jsonb, 'A', 1, '5e5ac4ed324a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log_b( m/n ) = 4 and log_b m = 7, then log_b n = ?', '["28","11","3","−3"]'::jsonb, 'C', 1, '5048b20439dd', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₅ 5⁷ × log₇ 7³ = ?', '["10","21","7","3"]'::jsonb, 'B', 1, 'e78aa54d049c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log 156.3 = ?', '["2.1939","1.1939","3.1939","2.9310"]'::jsonb, 'A', 1, 'aeba3a6d48b6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₂₅ 5 = ?', '["5","2","1/2","1/5"]'::jsonb, 'C', 1, '2e4a532748b5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log_b ( b³ × b⁻⁵ ) = ?', '["2","−3","8","−2"]'::jsonb, 'D', 1, '3aa02361b413', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log_b 2 = 0.3010 and log_b 3 = 0.4771, then log_b 72 = ?', '["1.8573","1.6532","2.1401","1.9542"]'::jsonb, 'A', 1, '53bbcaeb8f16', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₁₀ (0.001)² = ?', '["−3","6","−6","3"]'::jsonb, 'C', 1, '01d1beda9382', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log₂ x = log₄ 16, then x = ?', '["8","16","2","4"]'::jsonb, 'D', 1, 'fb36af604134', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log_b 2 = 0.3010, log_b 3 = 0.4771, log_b 5 = 0.6990, then log_b (6/5) = ?', '["0.0791","0.1761","0.2218","0.9542"]'::jsonb, 'A', 1, '3adace55e078', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Number of digits in 5⁵⁰ =', '["34","35","36","33"]'::jsonb, 'B', 1, 'dd41830453f6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log_b (y³+1) = log_b 28, then y = ?', '["2","4","3","5"]'::jsonb, 'C', 1, 'ce02038814f7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log₆₄ x = −4/3, then x = ?', '["1/16","1/256","256","16"]'::jsonb, 'B', 1, '99310aacbaca', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log 13/(7b) expanded is:', '["log 13 − log 7 + log b","log 13 − log 7 − log b","log 13 + log 7 − log b","log 13/(log 7 · log b)"]'::jsonb, 'B', 1, '965f12121034', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log 39 − log t − log b combined is:', '["log(39tb)","log(39/t + b)","log(39/tb)","log 39/log(tb)"]'::jsonb, 'C', 1, '68f31251acb1', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'antilog 2.4541 = ?', '["24.45","284.5","2845","0.2845"]'::jsonb, 'B', 1, '42efd44bb82e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log_y xwill be equal to:', '["(log_z x)/(log_y z)","(logₓ z)/(log_y z)","(log_z x)/(log_z y)","(log_z y)/(log_z x)"]'::jsonb, 'C', 1, '48a41a669336', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Integral part of the logarithm is called', '["Mantissa","Characteristic","Exponent","Base"]'::jsonb, 'B', 1, '73651ef585a4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Mantissa is always non- negative number less than', '["0","1","2","3"]'::jsonb, 'B', 1, '3c113b848840', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Logarithm of a number = -------------', '["2(Mantissa) + Characteristic","Characteristic + Mantissa","Characteristic – Mantissa","Mantissa – Characteristic"]'::jsonb, 'B', 1, 'a5390440999f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The inverse operation of taking log is called', '["Characteristic","Mantissa","Antilog","None of these"]'::jsonb, 'C', 1, 'a5f7a486642a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Logarithms with base ------- are called common logarithms.', '["10","e","-e","2"]'::jsonb, 'A', 1, 'd6c5ca8331e0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Antilog means to find a number whose -------- is given.', '["Characteristic","Mantissa","Log","None of these"]'::jsonb, 'C', 1, '3a5be6a4e921', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Decimal part or fractional part of a logarithm is called --------', '["Characteristic","Mantissa","Zero","None of these"]'::jsonb, 'B', 1, '690a732afc60', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log_b x=4 and log_b y=2 , what is log_b (x × y³) ?', '["5","7","9","10"]'::jsonb, 'D', 1, '3a33a8734ecb', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the value of x in the exponential equation 9 + e^(2x-4) = 10?', '["2","3","4","5"]'::jsonb, 'A', 1, '322bcfd0bfd2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Simplify: 10¹² ÷ 10⁵ ÷ 10³', '["10²⁰","10¹²","10¹⁰","10⁴"]'::jsonb, 'D', 1, '395a2b580bae', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log ( mⁿ) can be written as ----------', '["(log m)ⁿ","m log n","n log m","log (mn)"]'::jsonb, 'C', 1, '32c74d2ac849', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The relation y = log_z x implies', '["x^y=z","z^y = x","x²=y","y² = x"]'::jsonb, 'B', 1, 'b35d90c2a7fa', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is correctly written in scientific notation?', '["53.4 × 10³","0.534 × 10⁵","5.34 × 10⁴","53.4 × 10⁴"]'::jsonb, 'C', 1, '024b7551ac17', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '0.00000492 in scientific notation is:', '["4.92 × 10⁻⁵","4.92 × 10⁻⁶","49.2 × 10⁻⁷","0.492 × 10⁻⁵"]'::jsonb, 'B', 1, '1a05ec119c5e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '5.64 × 10⁰ in standard notation is:', '["56.4","0.564","5.64","564"]'::jsonb, 'C', 1, '03228f880dd4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '(563.71 × 10⁻²) × (2.54 × 10⁴) in scientific notation is:', '["1.432 × 10⁵","14.32 × 10⁴","1.432 × 10⁴","143.2 × 10³"]'::jsonb, 'A', 1, '757d57f29249', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The value of n in 0.00000000001 = 1 × 10ⁿ is:', '["10","−10","−11","11"]'::jsonb, 'C', 1, 'b56280205914', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '(0.023 × 10²) ÷ 10⁻² in standard notation equals:', '["230","2300","23","0.23"]'::jsonb, 'A', 1, 'e1914c643132', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₂ (log₃ 81) = ?', '["1","3","2","4"]'::jsonb, 'C', 1, '55661d2277b7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The number of digits in 1.5 × 10⁸ written in standard form is:', '["7","8","9","10"]'::jsonb, 'C', 1, 'c7acdeb58642', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₂ 128 = ?', '["6","7","8","9"]'::jsonb, 'B', 1, '8f0a2ee8fb60', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '125^(1/3) = 5 in logarithmic form is:', '["log₅ 125 = 3","log₁₂₅ 5 = 1/3","log₅ 125 = 1/3","log₃ 5= 125"]'::jsonb, 'B', 1, '7273699dacde', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₅ (-1) is :', '["−1","1","0","Undefined"]'::jsonb, 'D', 1, '0004f290c0bb', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log₂ (4-2x) = y, for which value of x is y undefined?', '["x = 0","x = 1","x = 2","x = −1"]'::jsonb, 'C', 1, 'a054b7c1f654', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The exponential form of log₈₁ (1/3) = −1/4 is:', '["81^(1/4) = 3","81^(-1/4)= 1/3","(1/3)⁸¹ = −1/4","3⁸¹ = 1/4"]'::jsonb, 'B', 1, '9a1d87aa9c56', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log_b b⁵ = x, then x = ?', '["b","5b","5","1/5"]'::jsonb, 'C', 1, 'f1d7f3b12cc0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The characteristic of log 3.3 × 10² is:', '["1","2","3","0"]'::jsonb, 'B', 1, '497b6327b4ab', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Mantissa is always:', '["Negative","An integer","Non-negative","Greater than 1"]'::jsonb, 'C', 1, 'ac001e4de0d6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If log_b x = log_b y, then which must be true?', '["b = 1","x = y","x + y = 0","b = x"]'::jsonb, 'B', 1, '03f9a93afb2b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If ln e⁴ = x, then x = ?', '["e","4","e⁴","1/4"]'::jsonb, 'B', 1, 'b9dc08c9743c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Number of digits in a whole number = characteristic + ?', '["0","2","1","−1"]'::jsonb, 'C', 1, '7eadc8d92262', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If characteristic of log of a number is 3, how many digits does that number have?', '["3","5","4","2"]'::jsonb, 'C', 1, '84a25ee94007', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which expression equals 1?', '["log_b ( m+n )","log_b b","log_b 0","log_b ( b+1 )"]'::jsonb, 'B', 1, '30d4ba79a9f7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log (x²y³z) expanded equals:', '["2 log x + 3 log y + log z","2 log x · 3 log y · log z","log 2x + log 3y + log z","6 log xyz"]'::jsonb, 'A', 1, '3227e9c4d828', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₃ 5 × log₅ 27 = ?', '["1","2","3","5"]'::jsonb, 'C', 1, '2d6663d57884', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log_b a × logₐ b = ?', '["0","log_b a","1","logₐ b"]'::jsonb, 'C', 1, '1e1bab969a6a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log₃ 536 converted to base 10 is:', '["log 536 × log 3","log 536 / log 3","log 3 / log 536","log ( 536/3)"]'::jsonb, 'B', 1, '05fb32e37a89', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log_b (50-5)equals:', '["log_b 50- log_b 5","log_b 45","log_b 50+ log_b 5","log_b 5 × log_b 10"]'::jsonb, 'B', 1, '3b777e860acc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'log (5p²q^(1/2))/(4√s t³) expanded fully is:', '["log 5 + 2logp + ½logq − log4 − ½logs − 3logt","log 5 + 2logp + ½logq + log4 + ½logs + 3logt","log 5 − 2logp − ½logq − log4 + ½logs − 3logt","log 5 + 2logp + ½logq − log4 + ½logs + 3logt"]'::jsonb, 'A', 1, '2183dc268f51', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The natural logarithm uses base:', '["10","2","e","π"]'::jsonb, 'C', 1, '1ca6bcc8f44d', null);
end $$;
