-- Maths chapter 1 — 30 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Maths' and c.seq = 1
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Maths chapter 1: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Let Q represent the set of Rational numbers and Q'' represent the set of Irrational numbers. What is the value of the operation Q ∩ Q''?', '["{0}","R","∅","Z"]'::jsonb, 'C', 1, '55102e63aa32', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following numbers belongs strictly to the set of Non-Integer Rational Numbers?', '["-12","0","- 13/25","√11"]'::jsonb, 'C', 1, 'f3fa227781b1', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a number x can be represented as a decimal that is non-terminating and non-recurring, to which set does it belong?', '["Natural Numbers (N)","Integers (Z)","Rational Numbers (Q)","Irrational Numbers (Q'')"]'::jsonb, 'D', 1, 'bba7e32f6990', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'According to the textbook layout, the set of Whole Numbers (W) is formed by taking the union of which two components?', '["Negative Integers and Natural Numbers","The element {0} and the set of Natural Numbers (N)","Rational Numbers and Irrational Numbers","Non-integer fractions and Positive Integers"]'::jsonb, 'B', 1, '68e33c8f72f9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following numbers is classified as a rational number that can be expressed as a terminating decimal?', '["1/3","7/8","√2","-π"]'::jsonb, 'B', 1, 'f0af938f4a4b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why is the square root of any non-perfect square integer (such as √11 or √23) automatically irrational?', '["Because its value on a number line is always less than zero.","Because it cannot be written as a terminating or repeating/recurring decimal representation.","Because it does not contain a base value.","Because it is a whole number multiple of zero."]'::jsonb, 'B', 1, '730c33d545fc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the structural difference between an open interval like -6 < x < 4 and a closed interval boundary on the real number line?', '["Open intervals only apply to irrational numbers.","Open intervals completely exclude the exact boundary value numbers from the solution set.","Closed intervals require the use of infinity symbols.","Open intervals cannot be translated into algebraic notation."]'::jsonb, 'B', 1, 'f5f40c2d69a6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Let x = -0.3̅ (or -0.333...). What is its precise structural classification?', '["Irrational number, because the decimal string continues to infinity without stopping.","Integer, because it lies directly on the left side of the zero origin point.","Rational number, because it features a non-terminating, recurring decimal pattern.","Natural number, because it belongs to a predictable sequence."]'::jsonb, 'C', 1, '11d577ff6f7b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which statement about the number 0 is universally true based on the properties outlined in Unit 1?', '["It is the multiplicative identity of real numbers.","It belongs to the set of Natural Numbers (N).","It is the additive identity of real numbers.","It is an irrational number because it has no value."]'::jsonb, 'C', 1, '2547664e9ef3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Every natural number is also automatically a member of which of the following sets?', '["Negative Integers","Non-Integer Rational Numbers","Irrational Numbers","Integers, Whole Numbers and Rational Numbers"]'::jsonb, 'D', 1, '568a2b4a2d83', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following numbers is a real number that is neither rational nor irrational?', '["√8","-4.5","There is no such number; every real number must be either rational or irrational.","0"]'::jsonb, 'C', 1, '8c8132bee26f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a set contains all values of x such that x > -4, which statement describes its true visual boundary configuration on a number line?', '["A solid dot at -4 with a shaded arrow extending infinitely to the left.","A hollow circle at -4 with a shaded arrow extending infinitely to the right.","A solid dot at 0 pointing towards -4.","A shaded segment trapped exclusively between -4 and 0."]'::jsonb, 'B', 1, '7c2c7e458f20', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The coordinate value point designated as the structural "origin" on a standard geometric number line corresponds to which real number?', '["1","-1","0","∞"]'::jsonb, 'C', 1, '6e2a98f84eae', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following represents an irrational number located between the positive integers 2 and 3?', '["7/8","√2","√8","4 1/2"]'::jsonb, 'C', 1, '6765e3aa0e0c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What real number property is exemplified by the expression: 4 + (6 + 8) = (4 + 6) + 8?', '["Commutative Property with respect to Addition","Associative Property with respect to Addition","Distributive Property of Multiplication over Addition","Closure Property with respect to Addition"]'::jsonb, 'B', 1, '9c7849bb72e2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following statements perfectly captures the operational rule of the Additive Inverse property?', '["a . 1 = a","a + (-a) = 0","a . 1/a = 1","a . b = 1"]'::jsonb, 'B', 1, '791d1e9b49f1', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which real number is identified as the only value that does not possess a multiplicative inverse?', '["1","-1","0","Every real number has a multiplicative inverse."]'::jsonb, 'C', 1, '9f8537576247', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What mathematical property justifies the step: (x + 2) + y = y + (x + 2)?', '["Associative Property of Addition","Commutative Property of Addition","Distributive Property","Reflexive Property of Equality"]'::jsonb, 'B', 1, 'dbe68e57b6a0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If 14 × 1/14 = 1, which real number property has been actively applied?', '["Multiplicative Identity Property","Multiplicative Inverse Property","Cancellation Property","Closure Property"]'::jsonb, 'B', 1, '312041764152', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the product of any real number a multiplied by the additive identity?', '["a","1","0","-a"]'::jsonb, 'C', 1, '2f53b5df2347', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which property is defined as: a(b + c) = ab + ac for all real numbers a, b and c?', '["Associative Property of Multiplication","Distributive Property of Multiplication over Addition","Commutative Property of Multiplication","Symmetric Property of Equality"]'::jsonb, 'B', 1, '4ff77896554d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The fact that adding any two real numbers together (a + b ∈ R) will always produce another perfectly valid real number is known as the:', '["Identity Property","Closure Property with respect to Addition","Transitive Property","Distributive Property"]'::jsonb, 'B', 1, 'adf5f8dbed8d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What property is highlighted by the equation: 6 × 4 = 4 × 6?', '["Commutative Property with respect to Multiplication","Associative Property with respect to Multiplication","Multiplicative Identity Property","Closure Property of Multiplication"]'::jsonb, 'A', 1, '98c1f58fe94c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the value of the expressions evaluated using the distributive property: 32 (1/8 + 1/4 )', '["8","10","12","16"]'::jsonb, 'C', 1, 'bca2cfd54f82', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If (0.2) . 5 = 1, then 0.2 and 5 are related to each other as:', '["Additive Inverses","Multiplicative Inverses","Additive Identities","Multiplicative Identities"]'::jsonb, 'B', 1, '8140ae33841a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What property justifies the following algebraic statement: a . 1 = 1 . a = a?', '["Multiplicative Inverse Property","Multiplicative Identity Property","Commutative Property of Addition","Trichotomy Property"]'::jsonb, 'B', 1, '3516ec11de84', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following operations is not associative over the set of real numbers?', '["Addition","Multiplication","Subtraction","Both Addition and Multiplication are non-associative."]'::jsonb, 'C', 1, 'b4478e7b3ed2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the additive inverse of the number 0?', '["1","-1","0","It does not exist."]'::jsonb, 'C', 1, 'c7c775647845', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a < b and both share the same sign, what happens to their reciprocals?', '["1/a< 1/b","1/a > 1/b","1/a = 1/b","The relationship stays exactly the same."]'::jsonb, 'B', 1, '6f77216470ba', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What happens to the inequality sign if a negative number is multiplied on both sides?', '["The inequality sign remains completely unchanged.","The inequalities are reversed.","The inequality changes into an equals sign.","The entire mathematical expression becomes zero."]'::jsonb, 'B', 1, '045565b221c6', null);
end $$;
