-- Maths chapter 3 — 41 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Maths' and c.seq = 3
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Maths chapter 3: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If A x B = B x A for two non- empty sets, what can you conclude about the sets?', '["They are disjoint","A = B","One is a proper subset of the other","They have no elements in common"]'::jsonb, 'B', 1, 'a04cf2db1a37', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If A ⊂ B (A is proper subset of B) , the Venn diagram shows:', '["Two separate circles","Two overlapping circles","Circle A completely inside circle B","Circles of equal size"]'::jsonb, 'C', 1, '4fd198cd4abf', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The distributive property A∪(B∩C) equals:', '["(A∪B)∩C","(A ∪B)∩(A∪C)","(A∩B)∪(A∩C)","A∩(B∪C)"]'::jsonb, 'B', 1, '92e261c64fe8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'For sets A and B : (A∪B)^ˊ equals (De Morganˊs Law).', '["A^ˊ∪ B^ˊ","A^ˊ ∩ B^ˊ","A∩B","A^ˊ ∪B"]'::jsonb, 'B', 1, '0b2651010a3a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If (2x+3 , y-1)=(7 , 4) is an equality of ordered pairs , find the unique values of x and y.', '["x=2 , y=5","x=5 , y=3","x=2 , y=3","x=1 , y=5"]'::jsonb, 'A', 1, '3d8f25b33af8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A binary relation R from set A to set B is:', '["Any function from A to B","A subset of A x B","Equal to A x B","A subset of A ∪ B"]'::jsonb, 'B', 1, 'f5098cdc6b6f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If A = {1,2,3} , B = {0,1,3} and R = { (a,b)/ a ∈A , b ∈ B, a > b }, then R is:', '["{ (1,0),(2,0),(2,1),(3,0),(3,1) }","{ (1,0),(2,1),(3,0),(3,1) }","{ (2,0),(2,1),(3,0),(3,1)(3,3) }","Both A and B are correct"]'::jsonb, 'A', 1, 'b64278eba338', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Shading only the central overlapping region where circles A and B cross represents:', '["A∪B","A-B","A∩B","A^ˊ"]'::jsonb, 'C', 1, '78fed2f69921', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If two circles inside a Venn diagram rectangle do not touch or overlap at any point, the sets are:', '["Equal","Overlapping","Disjoint","Universal"]'::jsonb, 'C', 1, 'e8017c403954', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a Venn diagram contains zero shaded regions, what set does the unshaded space represent?', '["Universal set","Empty set","Complement set","Infinite set"]'::jsonb, 'B', 1, 'edc1f253b0a8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Set building form of AՍB is .', '["{x/x ∈A v x∈B}","{x/x ∉ A ^ x ∈ B}","{x/x ∈ A ^ x ∉ B}","{x/x ∉ A ^ x ∉ B}"]'::jsonb, 'A', 1, '1aacf97c12ff', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The pictorial representation of any set is called a -----------', '["Binary relation","Real line","Venn diagram","None of these"]'::jsonb, 'C', 1, '47ca67578f60', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Dom R⁻¹ equals:', '["Domain of R","Range of R","A x B","None of these"]'::jsonb, 'B', 1, 'f8c1353320ae', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A x B = ∅ if and only if:', '["A = B","A ∩ B = ∅","A = ∅ or B = ∅","n(A) ≠ n(B)"]'::jsonb, 'C', 1, '4bec96365262', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'R₁ = ∅ is called ------', '["Empty set","Single set","A void relation","None of these"]'::jsonb, 'C', 1, '8ecf5e157277', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Set of multiples of 4 greater than and equal to 40 in set builder form is:', '["{4x/x∈N ∧x ≥10 }","{3x/x∈N ∧x ≥10 }","{2x/x∈N∧x≥10}","None of these"]'::jsonb, 'A', 1, '2f4492f86312', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Range R⁻¹ = ------', '["Domain of R","Range of R","Domain of R⁻¹","A x B"]'::jsonb, 'A', 1, 'e938804ac44d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Shading the entire area across both circles A and B , including their overlapping region , represents:', '["A ∩B","A ∪B","A-B","( A ∩B )^ˊ"]'::jsonb, 'B', 1, '9d4140ec0544', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The set {x/x∈U∧x∉A} is equal to:', '["A","A^ˊ","A-B","B^ˊ"]'::jsonb, 'B', 1, 'b6a53a736fc9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '{ ∅ } is a ------------- set.', '["Empty set","Subset","Singleton set","None of these"]'::jsonb, 'C', 1, '6fceb187fd08', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is a well defined set?', '["A collection of tall students","A set of prime numbers less than 20","A set of beautiful paintings","A collection of good books"]'::jsonb, 'B', 1, '96172777c7d1', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If A = {x/x∈N⋀x²=4} , then A equals:', '["{ 2,-2}","{ 2 }","{ 4 }","{ }"]'::jsonb, 'B', 1, '06d44473879f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If A = { 1,2,3,4,5} and B = { 3,4,1,7,6}, then A∪B is:', '["{ 3, 4,1 }","{ 1, 2, 3, 4, 5, 6, 7 }","{ 1,2,3,5,7 }","Both B and C"]'::jsonb, 'B', 1, '7328675826a2', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If A = { a, b, c, d } and B = { c, d, e, f }, then A∩B is:', '["{ a, b, c, d,e,f }","{ c, d }","{ a, b, e, f }","{ }"]'::jsonb, 'B', 1, '23593416446b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If U = { 1, 2, 3, 4, 5, 6,7 } and A = { 2,4,6 }, then Aˊ equals:', '["{ 1,3,5,7}","{2,4,6}","{1,2,3,5,7}","{1.3.4.5,7}"]'::jsonb, 'A', 1, '2799f37d55c6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'For any set A: A ∩Aˊ equals:', '["A","∅","U","Aˊ"]'::jsonb, 'B', 1, '1b7b87e1ed97', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'For any set A: A ∩ ∅ equals:', '["A","∅","U","Aˊ"]'::jsonb, 'B', 1, '51692d2ec5bc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two sets A and B are disjoint if:', '["A⊂B","A∩B = ∅","A∪B = ∅","n(A) = n(B)"]'::jsonb, 'B', 1, 'a295fc180a25', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The associative property of union states:', '["A ∪ B = B ∪ A","( A ∪ B ) ∪ C = A ∪ ( B ∪ C )","A ∪(B∩C) = (A∪B)∩(A∪C)","A ∪ ∅ = A"]'::jsonb, 'B', 1, '77d007b1051b', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If A = { 1,2,3}, B= {2,3,4}, C= {3,4,5}, Verify (A∩B)∩C:', '["{ 3 }","{ 2,3 }","{ 3,4 }","{2,3,4 }"]'::jsonb, 'A', 1, 'a179eff280cd', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two ordered pairs (a,b) and (c,d) are equal if:', '["a = d and b = c","a = c and b = d","a = b and c = d","a + b = c + d"]'::jsonb, 'B', 1, '06b9354b7ac1', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The domain of R = {(1,0),(2,0),(2,1),(3,0),(3,1)} is:', '["{0,1}","{1,2,3}","{0,1,2,3}","{1,2,3,4}"]'::jsonb, 'B', 1, '9c7b7b2f384e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The range of R = { (1,0),(2,0),(2,1),(3,0),(3,1)} is:', '["{ 0,1 }","{ 1,2,3 }","{ 0,1,2,3 }","{ }"]'::jsonb, 'A', 1, '93dc33b17d2f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'R⁻¹ of R = { (0,0),(2,4),(3,9)} is :', '["{ (0,0),(4,2),(9,3) }","{ (0,0),(2,4),(3,9) }","{ (4,0),(9,3)}","Cannot be determined"]'::jsonb, 'A', 1, 'a5d51948dd9e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If R = { (x,y)/∈A, y∈A, x²=y} and A = {0,2,3}, then R is:', '["{ (0,0),(2,4),(3,9) }","{ (0,0) }","{ }","Undefined since 4,9 ∉ A"]'::jsonb, 'B', 1, 'c0aeda7e17f1', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If L x M = {(0,2),(0,3),(0,4),(1,2),(1,3),(1,4)} , then set L is:', '["{ 0,1 }","{ 2,3,4 }","{ 0,1,2,3,4 }","Cannot determine"]'::jsonb, 'A', 1, '44ee976f4e46', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If L x M = {(0,2),(0,3),(0,4),(1,2),(1,3),(1,4)} , then set M is:', '["{ 0,1 }","{ 2,3,4 }","{ 0,1,2,3,4 }","Cannot determine"]'::jsonb, 'B', 1, 'c6b54362e1af', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A ------- is a collection of well defined and distinct objects.', '["Disjoint","Set","Union","Intersection"]'::jsonb, 'B', 1, '8203f5b6acf0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If B = {x/x∈N⋀2<x≤3} , which set best describe B?', '["Empty set","Singleton set","Infinite set","Null set"]'::jsonb, 'B', 1, '0bc0ba928448', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Let U = { 1,2,3,…….,10} , A = { 2,4,6,8,10} and B = { 1,3,5,7,9 }. Find (A∪B)^ˊ.', '["U","∅","{2,4,6}","{1,3,5}"]'::jsonb, 'B', 1, 'be87b9e23e24', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Let A = { 1,2 } and B = { a,b }. Find the complete Cartesian product set A x B.', '["{ (1,a) ,(2,b) }","{ ( 1,a) , (1,b) , (2,a) ,(2, b)}","{ (a,1) , (b,1) ,( a,2) , (b, 2)}","{ 1,2,a,b}"]'::jsonb, 'B', 1, '087d86320dfe', null);
end $$;
