-- Maths chapter 4 — 30 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Maths' and c.seq = 4
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Maths chapter 4: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factorization of 15x²y as a product of its factors is:', '["(15x)(y)","(5x)(3xy)","(5x²)(3xy)","(3x)(5y)"]'::jsonb, 'B', 1, '6aea772a7569', '15x²y = (5x)(3xy). This is direct product factorization; 5x × 3xy = 15x²y.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factorization of a⁴ + a²b² + b⁴ is:', '["(a² + ab)(a² − ab)","(a + b)²(a − b)²","(a² + b² + ab)(a² + b² − ab)","(a² + b²)²"]'::jsonb, 'C', 1, '3d4e6e7ec19b', 'a⁴ + a²b² + b⁴: add and subtract a²b² to form (a² + b²)² − (ab)² = (a² + b² + ab)(a² + b² − ab).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'a⁴ + 64b⁴ factorizes as:', '["(a² + 8b² + 4ab)(a² + 8b² − 4ab)","(a² + 4b)(a² − 4b)","(a + 4b)²(a − 4b)²","(a² + 8b²)²"]'::jsonb, 'A', 1, 'c965a6ff10f9', 'a⁴ + 64b⁴ = (a² + 8b²)² − (4ab)² = (a² + 8b² + 4ab)(a² + 8b² − 4ab).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is the factored form of x⁴ + 4m⁴?', '["(x² + 2m)²","(x + 2m)²(x − 2m)²","(x² − 2m²)²","(x² + 2m² + 2xm)(x² + 2m² − 2xm)"]'::jsonb, 'D', 1, '8a34b871cd73', 'x⁴ + 4m⁴ = (x² + 2m²)² − (2xm)² = (x² + 2m² + 2xm)(x² + 2m² − 2xm).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of y² − 7y + 12 is:', '["(y + 3)(y + 4)","(y − 6)(y − 2)","(y − 3)(y − 4)","(y − 12)(y + 1)"]'::jsonb, 'C', 1, 'a6f2034ba9c5', 'y² − 7y + 12: factors of 12 with sum −7 are −3 and −4 → (y − 3)(y − 4).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of m² − 2m − 15 is:', '["(m − 5)(m + 3)","(m + 5)(m − 3)","(m − 15)(m + 1)","(m + 15)(m − 1)"]'::jsonb, 'A', 1, '960260c7ff61', 'm² − 2m − 15: factors of −15 with sum −2 are −5 and +3 → (m − 5)(m + 3).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of 3x² + 22x − 16 is:', '["(x − 8)(3x + 2)","(x + 4)(3x − 4)","(3x + 8)(x − 2)","(x + 8)(3x − 2)"]'::jsonb, 'D', 1, '4f0f9cac8a1d', '3x² + 22x − 16: product = −48; pair with sum 22 is 24, −2 → 3x² + 24x − 2x − 16 = (x + 8)(3x − 2).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of x² + x − 2 is:', '["(x − 2)(x + 1)","(x + 2)(x − 1)","(x + 2)(x + 1)","(x − 2)(x − 1)"]'::jsonb, 'B', 1, 'cacacfc93c3d', 'x² + x − 2: factors of −2 with sum +1 are +2 and −1 → (x + 2)(x − 1).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When factorizing (x² + 3x − 4)(x² + 3x + 5) + 8, substituting a = x² + 3x gives:', '["(a + 4)(a + 5) + 8","(a + 4)(a − 5) + 8","(a − 4)(a + 5) + 8","(a − 4)(a − 5) + 8"]'::jsonb, 'C', 1, '6b452e58dc8c', 'Substituting a = x² + 3x, the expression becomes (a − 4)(a + 5) + 8.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of (x² + 3x − 4)(x² + 3x + 5) + 8 is:', '["(x² + 3x + 4)(x² + 3x − 3)","(x² + 3x − 4)(x² + 3x + 1)","(x² + 3x + 2)(x² + 3x − 1)","(x + 4)(x + 3)(x − 1)(x − 3)"]'::jsonb, 'A', 1, 'e1d7f64035d1', '(a − 4)(a + 5) + 8 = a² + a − 12 = (a + 4)(a − 3); replacing a gives (x² + 3x + 4)(x² + 3x − 3).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The identity a³ + 3a²b + 3ab² + b³ equals:', '["a³ + b³","(a − b)³","(a + b)(a² − ab + b²)","(a + b)³"]'::jsonb, 'D', 1, 'dfb3cbe5c7ca', 'Binomial cube identity: a³ + 3a²b + 3ab² + b³ = (a + b)³.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of 27a³ + 1 + 27a² + 9a is:', '["(3a − 1)³","(3a + 1)³","(3a + 1)(9a² − 3a + 1)","(3a)³ + 1"]'::jsonb, 'B', 1, '549b0619a205', '27a³ + 27a² + 9a + 1 = (3a)³ + 3(3a)²(1) + 3(3a)(1²) + 1³ = (3a + 1)³.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The expression 8x³ − 60x² + 150x − 125 factorizes as:', '["(2x + 5)³","(x − 5)³","(2x − 5)³","(4x − 5)³"]'::jsonb, 'C', 1, '15057d4de6b1', '8x³ − 60x² + 150x − 125 = (2x)³ − 3(2x)²(5) + 3(2x)(5²) − 5³ = (2x − 5)³.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'a³ + b³ factorizes as:', '["(a + b)(a² − ab + b²)","(a − b)(a² + ab + b²)","(a + b)(a² + ab + b²)","(a + b)(a − b)²"]'::jsonb, 'A', 1, '63e3af549dfa', 'Sum of cubes: a³ + b³ = (a + b)(a² − ab + b²).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of x³ + 27y³ is:', '["(x + 27y)(x² − 3xy + y²)","(x − 3y)(x² + 3xy + 9y²)","(x + 3y)³","(x + 3y)(x² − 3xy + 9y²)"]'::jsonb, 'D', 1, 'e8f95546f262', 'x³ + 27y³ = x³ + (3y)³ = (x + 3y)(x² − 3xy + 9y²).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The factored form of 8a³ − 125b³ is:', '["(2a + 5b)(4a² − 10ab + 25b²)","(2a − 5b)(4a² + 10ab + 25b²)","(2a − 5b)³","(2a − 5b)(4a² − 25b²)"]'::jsonb, 'B', 1, '2c0ec0731312', '8a³ − 125b³ = (2a)³ − (5b)³ = (2a − 5b)[(2a)² + (2a)(5b) + (5b)²] = (2a − 5b)(4a² + 10ab + 25b²).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The HCF of 18ab³c, 30a²b⁴c³, and 24b²c⁵ is:', '["6ab³c³","18b²c","6b²c","6b³c"]'::jsonb, 'C', 1, '5fd40d130511', 'HCF of coefficients 18, 30, 24 is 6; least power of b is b², least power of c is c → HCF = 6b²c.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The HCF of two or more polynomials is the polynomial that:', '["divides each of them exactly and is of highest degree","is divisible by each of them","is the product of all their factors","has the lowest degree among all factors"]'::jsonb, 'A', 1, '49445a288c7f', 'The HCF of polynomials divides each of them exactly and is of the highest possible degree.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The HCF of x² − 49 and x² − 4x − 21 is:', '["x² − 49","(x − 7)(x + 7)","x + 7","x − 7"]'::jsonb, 'D', 1, '4d1027e46235', 'x² − 49 = (x−7)(x+7); x² − 4x − 21 = (x−7)(x+3). The common factor is x − 7.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When finding the HCF of monomials, the HCF of the variable part is determined by taking:', '["the highest power of each variable","the lowest power of each common variable","the product of all powers","the sum of all powers"]'::jsonb, 'B', 1, '5d0097d1b875', 'For monomials, variable HCF = lowest power of each common variable appearing in all terms.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The LCM of two polynomials P and Q with HCF H is given by:', '["LCM = P × Q × H","LCM = H ÷ (P × Q)","LCM = (P × Q) ÷ H","LCM = (P + Q) ÷ H"]'::jsonb, 'C', 1, '7ffce99c437e', 'LCM = (P × Q) ÷ HCF. This is the standard formula relating LCM, HCF and the two polynomials.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The product of two polynomials P and Q equals:', '["HCF × LCM","HCF + LCM","HCF ÷ LCM","LCM ÷ HCF"]'::jsonb, 'A', 1, '19e9cbc0d1b8', 'P × Q = HCF × LCM is the fundamental theorem for any two polynomials.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If HCF of two polynomials is x − 7 and their LCM is x³ − 10x² + 11x + 70, their product is:', '["(x − 7) + (x³ − 10x² + 11x + 70)","(x − 7) ÷ (x³ − 10x² + 11x + 70)","Cannot be determined","(x − 7)(x³ − 10x² + 11x + 70)"]'::jsonb, 'D', 1, 'b03e333fb01c', 'Product = HCF × LCM = (x − 7)(x³ − 10x² + 11x + 70).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'An algebraic fraction P/Q is defined when:', '["Q = 0 always","P and Q are polynomials and Q ≠ 0","P and Q are integers only","P and Q are constants"]'::jsonb, 'B', 1, '831f7548aa75', 'An algebraic fraction P/Q requires P and Q to be polynomials with Q ≠ 0.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To add algebraic fractions with different denominators, we first find their:', '["HCF","Product","LCM","Difference"]'::jsonb, 'C', 1, '09ca91032911', 'A common denominator (LCM of denominators) is required before adding algebraic fractions.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The simplified form of the fraction (x²- 9)/(x +3) is:', '["x – 3","x + 3","x² − 3","(x − 3)(x + 3)"]'::jsonb, 'A', 1, 'a0f14535a092', '(x² − 9)/(x + 3) = (x + 3)(x − 3)/(x + 3) = x − 3, valid for x ≠ −3.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To divide one algebraic fraction by another, we multiply the first fraction by:', '["the LCM of denominators","the HCF of numerators","the second fraction itself","the reciprocal of the second fraction"]'::jsonb, 'D', 1, '555c5b32e0cb', '(P/Q) ÷ (R/S) = (P/Q) × (S/R): multiply by the reciprocal of the divisor fraction.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The square root of a perfect square polynomial can be found by:', '["addition only","factorization or division method","long division of integers only","substitution only"]'::jsonb, 'B', 1, '2b9f34689569', 'Square roots of algebraic expressions are found by factorization method or division method.'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The square root of 9x² − 42xy + 49y² is:', '["±(9x − 7y)","±(3x + 7y)","±(3x − 7y)","±(3x − 49y)"]'::jsonb, 'C', 1, '8e940b5af450', '9x² − 42xy + 49y² = (3x − 7y)² → square root = ±(3x − 7y).'),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The expression x⁴ − 6x³ + 17x² − 24x + 16 has the square root:', '["±(x² − 3x + 4)","±(x² + 3x − 4)","±(x² − 3x − 4)","±(x + 3x − 4)"]'::jsonb, 'A', 1, 'a1f5e2f56ff5', 'x⁴ − 6x³ + 17x² − 24x + 16 = (x² − 3x + 4)² → square root = ±(x² − 3x + 4).');
end $$;
