-- Maths chapter 6 — 37 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Maths' and c.seq = 6
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Maths chapter 6: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the sexagesimal system, one degree (1°) is equal to:', '["60 minutes","100 minutes","60 seconds","3600 minutes"]'::jsonb, 'A', 1, '0742698e45e0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'How many seconds are there in one degree?', '["60″","360″","600″","3600″"]'::jsonb, 'D', 1, '4d2ef2c1badf', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The radian measure of a complete angle (360°) is:', '["π radians","3π/2 radians","2π radians","4π radians"]'::jsonb, 'C', 1, 'd85533671951', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1 radian is approximately equal to:', '["45° 00′ 00″","57° 17′ 45″","60° 00′ 00″","90° 00′ 00″"]'::jsonb, 'B', 1, '27c1c6621cdc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To convert an angle from degrees to radians, multiply by:', '["π/360","π/180","180/π","360/π"]'::jsonb, 'B', 1, '62158f33d5f3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The radian measure of 90° is:', '["π/4","π/3","π/2","π"]'::jsonb, 'C', 1, '085f7cf53ff8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The length of a circular arc with radius r and central angle θ (in radians) is:', '["l = r²θ","l = rθ","l = θ/r","l = 2πr/θ"]'::jsonb, 'B', 1, '7fe9b18b1c27', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The area of a sector of a circle with radius r and central angle θ radians is:', '["A = rθ","A = r²θ","A = ½ r²θ","A = πr²θ"]'::jsonb, 'C', 1, '52702de3d521', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A circle has radius 6 cm and its sector has a central angle of π/3 radians. What is the arc length?', '["π cm","2π cm","3π cm","6π cm"]'::jsonb, 'B', 1, '028638829b9f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a right-angled triangle ABC with ∠C = 90°, sin θ is defined as:', '["Base / Hypotenuse","Perpendicular / Hypotenuse","Perpendicular / Base","Hypotenuse / Perpendicular"]'::jsonb, 'B', 1, 'f4d123905711', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is the reciprocal of cos θ?', '["sin θ","tan θ","cosec θ","sec θ"]'::jsonb, 'D', 1, 'b034ca409684', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The value of tan 45° is:', '["0","1/(√2)","1","√3"]'::jsonb, 'C', 1, '193faed2e3fe', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The value of sin 30° is:', '["1","(√3)/2","1/(√2)","1/2"]'::jsonb, 'D', 1, '49347d8d2d96', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The value of cos 60° is:', '["(√3)/2","1/2","1/(√2)","0"]'::jsonb, 'B', 1, '215f2ff3b24f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'sin 90° is equal to:', '["0","1/2","(√3)/2","1"]'::jsonb, 'D', 1, 'aa4089c2bc52', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The value of cos 180° is:', '["1","0","−1","undefined"]'::jsonb, 'C', 1, '994849ef0751', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'tan 90° is:', '["0","1","−1","undefined"]'::jsonb, 'D', 1, '611dbe442b9c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'cot θ is equal to:', '["(sin θ)/(cos θ)","(cos θ)/(sin θ)","1/(sin θ)","1/(sec θ)"]'::jsonb, 'B', 1, 'c330d88a000c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In which quadrant are both sin θ and cos θ positive?', '["1st quadrant","2nd quadrant","3rd quadrant","4th quadrant"]'::jsonb, 'A', 1, 'bf7f7ca0195c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the second quadrant, which trigonometric ratio is positive?', '["cos θ","tan θ","sin θ","cot θ"]'::jsonb, 'C', 1, '9f2e1357d6b4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In the third quadrant, which of the following is positive?', '["sin θ","cos θ","tan θ","sec θ"]'::jsonb, 'C', 1, 'f7168a91cf7c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is a Pythagorean identity?', '["sin²θ − cos²θ = 1","sin²θ + cos²θ = 1","sin θ + cos θ = 1","sin²θ × cos²θ = 1"]'::jsonb, 'B', 1, '7294ddabf03d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'sec²θ − tan²θ equals:', '["0","−1","2","1"]'::jsonb, 'D', 1, '5fef42d95097', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'cosec²θ − cot²θ equals:', '["2","−1","1","0"]'::jsonb, 'C', 1, '9a03e4877f35', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'tan θ is equal to:', '["(cos θ)/(sin θ)","(sin θ)/(cos θ)","sin θ × cos θ","1/(cos θ)"]'::jsonb, 'B', 1, 'e3887cd80f97', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The angle of elevation is measured:', '["Below the horizontal line","Along the vertical","Above the horizontal line","Along the ground"]'::jsonb, 'C', 1, 'f2a3930e2da4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The angle between the horizontal line and the line of sight to an object below the observer is called:', '["Angle of elevation","Angle of depression","Angle of incidence","Bearing angle"]'::jsonb, 'B', 1, 'a4f158b44932', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A vertical pole is 10 m high. The angle of elevation of its top from a point on the ground is 45°. The distance of the point from the base of the pole is:', '["5 m","10/(√2) m","10 m","20 m"]'::jsonb, 'C', 1, '053892816ded', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A ladder 10 m long leans against a vertical wall making an angle of 60° with the wall. The height of the ladder along the wall is:', '["10√3 m","5 m","10 m","5√3 m"]'::jsonb, 'B', 1, '3749ee6ef41c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Bearings are measured clockwise from:', '["East","South","West","North"]'::jsonb, 'D', 1, '81a04db4f4c6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A three-figure bearing is always written using exactly:', '["1 digit","2 digits","3 digits","4 digits"]'::jsonb, 'C', 1, '138f0c6d14fc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The three-figure bearing of due East is:', '["000°","090°","180°","270°"]'::jsonb, 'B', 1, 'bbc14757aa91', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The three-figure bearing of due South is:', '["090°","135°","180°","270°"]'::jsonb, 'C', 1, '04ab4dd0416e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The three-figure bearing of due West is:', '["090°","180°","270°","360°"]'::jsonb, 'C', 1, 'df3948e04001', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The bearing of the South-West direction is:', '["045°","135°","225°","315°"]'::jsonb, 'C', 1, 'da5013f7a567', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'North-East direction has a bearing of:', '["045°","090°","135°","315°"]'::jsonb, 'A', 1, '28cbbc9de6d8', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If an automobile travels at a bearing of 070° from city A to city B, the bearing from city B back to city A is:', '["070°","110°","250°","290°"]'::jsonb, 'C', 1, '02d8cea44d32', null);
end $$;
