-- Maths chapter 5 — 30 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Maths' and c.seq = 5
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Maths chapter 5: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which one is the standard form of a linear equation in one variable?', '["ax² + b = 0","ax + b = 0","ax + by = 0","ax² + bx + c = 0"]'::jsonb, 'B', 1, '3435bd82ed14', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the exponent of the variable in a linear equation?', '["0","1","2","-1"]'::jsonb, 'B', 1, '57da21f25a46', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is a linear equation in one variable?', '["x² + 3 = 0","xy + 3 = 0","2x + 3 = 0","x² + 2x = 0"]'::jsonb, 'C', 1, '181778d763ab', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two or more equations that have the same solution are called:', '["Compound equations","Equivalent equations","Radical equations","Absolute equations"]'::jsonb, 'B', 1, 'bafdaf35cec6', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution of 5x − 2 − x = 4 − 3x − 27?', '["x = −3","x = −5","x = 5","x = 3"]'::jsonb, 'A', 1, 'd8f5f46a3d28', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Solve for x: 0.5x = 6.3 − 0.2x', '["x = 6","x = 7","x = 8","x = 9"]'::jsonb, 'D', 1, '157000326014', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To clear fractions while solving a linear equation, all terms are multiplied by the:', '["GCF of denominators","Product of denominators","LCM of denominators","Sum of denominators"]'::jsonb, 'C', 1, 'c66ddcc78842', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution of (x-2)/2 + (x+10)/9 = 5?', '["x = 4","x = 6","x = 8","x = 10"]'::jsonb, 'C', 1, '211c49d0dac5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which property of equality is applied when both sides of −2x = 2/5 are divided by −2 to solve for x?', '["Addition property","Subtraction property","Division property","Multiplication property"]'::jsonb, 'C', 1, 'cf923cfe0687', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'An equation in which the variable appears under a radical sign is called a:', '["Linear equation","Radical equation","Absolute value equation","Compound equation"]'::jsonb, 'B', 1, 'f01543629252', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of √2x = 4?', '["{2}","{4}","{8}","{16}"]'::jsonb, 'C', 1, '4c47ce3211e4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of √(x-3)= 2?', '["{1}","{5}","{7}","{9}"]'::jsonb, 'C', 1, '1edce8049605', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'While solving a radical equation, both sides of the equation are:', '["Added","Subtracted","Squared","Divided"]'::jsonb, 'C', 1, 'abfed2b29a63', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A root obtained after squaring that does not satisfy the original radical equation is called:', '["A rational root","An extraneous root","An equivalent root","A compound root"]'::jsonb, 'B', 1, '26f6c61aefe7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of √(5x-4)= -14?', '["{4}","{8}","{40}","φ (no solution)"]'::jsonb, 'D', 1, 'd59fa24d816a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The absolute value of a real number x represents its distance from:', '["1 on the number line","x on the number line","0 on the number line","−1 on the number line"]'::jsonb, 'C', 1, 'c1b8ecb7e1dc', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of |x| = 8?', '["{8}","{−8}","{−8, 8}","φ"]'::jsonb, 'C', 1, '379a68d5141a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of |x| = −6?', '["{6}","{−6}","{−6, 6}","φ"]'::jsonb, 'D', 1, 'd437a58ebc66', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of |x + 2| = 6?', '["{4, −8}","{4, 8}","{−4, −8}","{−4, 8}"]'::jsonb, 'A', 1, '0d27051bb436', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If |x| = k where k < 0, then the solution set of the equation is:', '["{k}","{−k, k}","{0}","φ"]'::jsonb, 'D', 1, 'f4546543490c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of |2x − 1| = 5?', '["{−2, 3}","{2, −3}","{2, 3}","{−2, −3}"]'::jsonb, 'A', 1, '3b1fdcc952ec', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A statement that two algebraic expressions are not equal is called:', '["An equation","An inequality","An identity","A radical"]'::jsonb, 'B', 1, 'd7c6500c426a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which one of the following is a strict inequality?', '["x + 3 ≠ 0","12x > 5","2y − 3 ≤ 0","4x + 5 ≥ 0"]'::jsonb, 'B', 1, 'ee9a0430b334', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When both sides of an inequality are multiplied or divided by a negative number, the inequality symbol:', '["Remains the same","Is reversed","Becomes an equality","Is removed"]'::jsonb, 'B', 1, 'b9afab381ca9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of 8x + 9 < 6x − 7?', '["{x | x ∈ R ∧ x < −8}","{x | x ∈ R ∧ x > −8}","{x | x ∈ R ∧ x < 8}","{x | x ∈ R ∧ x > 8}"]'::jsonb, 'A', 1, 'd8a4028c8aa5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A compound inequality formed by joining two inequalities with the word “and” is true when:', '["At least one inequality is true","Both inequalities are true","Exactly one inequality is true","Neither inequality is true"]'::jsonb, 'B', 1, '4f2883293ba5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'For a compound inequality joined by “or”, the solution set is the:', '["Union of both solution sets","Intersection of both solution sets","Difference of both solution sets","Product of both solution sets"]'::jsonb, 'A', 1, 'efd61a2786b5', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the solution set of the compound inequality x − 5 ≥ −1 and x + 3 ≤ 10, x ∈ R?', '["{x | x ∈ R ∧ 4 ≤ x ≤ 7}","{x | x ∈ R ∧ x ≤ 7}","{x | x ∈ R ∧ x ≥ 4}","{x | x ∈ R ∧ x < 4}"]'::jsonb, 'A', 1, '6f7a097df044', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If 5 ≥ 1 and 1 ≥ 1 are both true, then by the transitive property, which statement must also be true?', '["5 ≤ 1","1 ≥ 5","5 ≥ 1","5 = 1"]'::jsonb, 'C', 1, '62d9221edcf8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The sum of five times a number x and 10 is less than −35. What inequality represents this statement?', '["5x + 10 < −35","5x − 10 < −35","5(x + 10) < −35","5x + 10 > −35"]'::jsonb, 'A', 1, 'ba5b26d909aa', null);
end $$;
