-- Physics chapter 3 — 38 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 3
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 3: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A book is resting on a table. Which force prevents it from passing through the table?', '["Frictional force","Tension force","Normal force","Magnetic force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A person pulls a bucket upward using a rope. The force transmitted through the rope is:', '["Normal force","Elastic force","Tension force","Gravitational force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A cricketer catches a fast-moving ball by moving his hands backward. This reduces:', '["Momentum","Impulse","Force of impact","Mass"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two students push a box equally in opposite directions. The box remains at rest because:', '["No force acts","Resultant force is zero","Friction is absent","Weight becomes zero"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which force is responsible for keeping planets in orbit around the Sun?', '["Magnetic force","Electrostatic force","Gravitational force","Nuclear force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A parachute slows a falling skydiver mainly because of:', '["Tension","Normal force","Air resistance","Magnetic force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a person walks, the forward motion is possible because of:', '["Gravitational force","Friction between foot and ground","Tension","Electrostatic force"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'An astronaut''s mass on the Moon compared with Earth is:', '["Greater","Smaller","Same","Zero"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'An astronaut''s weight on the Moon is:', '["Same as on Earth","Greater than on Earth","Less than on Earth","Zero"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which pair represents contact forces only?', '["Friction and tension","Gravity and magnetism","Electrostatic and magnetic","Gravity and tension"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A magnet attracts an iron nail without touching it. This demonstrates:', '["Contact force","Elastic force","Non-contact force","Normal force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The strongest fundamental force is:', '["Gravitational","Electromagnetic","Weak nuclear","Strong nuclear"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which force is weakest but has an infinite range?', '["Strong nuclear","Weak nuclear","Gravitational","Frictional"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A truck and a bicycle have the same speed. Which has greater momentum?', '["Bicycle","Truck","Same","Cannot be determined"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Doubling the mass of a moving object while keeping velocity constant will:', '["Halve momentum","Double momentum","Triple momentum","Leave momentum unchanged"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why is it difficult to stop a loaded truck than an empty one moving at the same speed?', '["Greater friction","Greater momentum","Smaller inertia","Less force"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If Earth suddenly had twice its present gravitational field strength, a person''s:', '["Mass and weight would double.","Mass would double, weight unchanged.","Weight would double, mass unchanged.","Both remain unchanged."]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A ball is thrown vertically upward. At the highest point:', '["Velocity and acceleration are zero.","Velocity is zero but acceleration is not.","Acceleration is zero but velocity is not.","Momentum is maximum."]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two objects have equal momentum. Object X has twice the mass of object Y. Therefore:', '["X has twice the velocity of Y.","Y has twice the velocity of X.","Velocities are equal.","Insufficient information."]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A satellite moves in a circular orbit at constant speed. Which statement is correct?', '["Its acceleration is zero.","Net force is zero.","Velocity changes continuously.","Momentum remains constant."]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A heavier object has greater inertia because it has:', '["Greater weight","Greater mass","Greater volume","Greater density"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A swimmer pushes water backward and moves forward due to:', '["Inertia","Conservation of energy","Newton''s Third Law","Weight"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A force can change all EXCEPT:', '["Speed","Direction","Shape","Mass"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If mass doubles and acceleration remains constant, force becomes:', '["Half","Double","Four times","Same"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which statement about action and reaction forces is correct?', '["They act on the same object","They cancel each other","They act on different objects","One is larger"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Passengers in a bus fall forward when brakes are applied because:', '["Their bodies want to move forward.","Their upper bodies continue moving due to inertia.","Gravity increases suddenly.","Friction becomes zero."]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A force of 20 N acts on a body and produces an acceleration of 4 m/s². If the same force acts on a body of double mass, the acceleration will be:', '["8 m/s²","4 m/s²","2 m/s²","1 m/s²"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A gun recoils when a bullet is fired. Which statement best explains why the bullet moves much faster than the gun?', '["Bullet experiences a larger force.","Gun experiences a smaller force.","Bullet has much smaller mass.","Bullet has greater inertia."]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why are airbags installed in cars?', '["They reduce momentum.","They reduce mass.","They increase collision time.","They reduce inertia."]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A force F gives an acceleration of 4 m/s² to a body weighing 98 N. To produce an acceleration of 8 m/s² in the same body, the required force is:', '["F/2","F","2F","4F"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A force of 8 N is applied to a body weighing 12 N. The acceleration produced is:', '["0.67 m/s²","6.67 m/s²","9.8 m/s²","12 m/s²"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which force holds protons together inside the nucleus?', '["Gravitational force","Electromagnetic force","Strong nuclear force","Weak nuclear force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which force is responsible for radioactive decay?', '["Gravitational force","Electromagnetic force","Strong nuclear force","Weak nuclear force"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The electroweak theory combines:', '["Gravitational and strong forces","Strong and weak forces","Electromagnetic and weak forces","Gravitational and electromagnetic forces"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Newton''s laws of motion are not suitable for objects moving with:', '["Low speed","Uniform speed","Very high-speed close to the speed of light","Zero speed"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1 Newton''s laws are not applicable to the motion of:', '["Large-scale objects","Small-scale objects","Falling objects","Moving vehicles"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'According to Newton’s second law F=ma, a force of 1N is fundamentally equivalent to which combination of SI base units?', '["1kg⋅m/s","1kg⋅m/s2","1kg2⋅m/s","1m2⋅kg/s"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The unit of impulse (N s) can be mathematically shown to be completely identical to the unit of which other physical quantity?', '["Acceleration","Velocity","Mass","Linear Momentum"]'::jsonb, 'D', 1);
end $$;
