-- Physics chapter 4 — 35 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 4
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 4: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The direction of centripetal force is:', '["Tangential to the circle","Away from the center","Towards the center","Upward"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 300 N boy sits 2 m from the pivot of a seesaw. A 200 N boy can balance it by sitting:', '["2 m away","3 m away","1.5 m away","4 m away"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A door opens more easily when pushed far from the hinge because:', '["Friction decreases","Torque increases due to larger moment arm","Force increases automatically","Weight decreases"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A force is applied directly through the pivot point of a lever. The torque produced is:', '["Maximum","Minimum but non-zero","Zero","Depends on mass"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 2 kg ball moves in a circle of radius 4 m with speed 8 m/s. Centripetal force is:', '["16 N","24 N","32 N","48 N"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a stone tied to a string is whirled in a circle and the string breaks, the stone moves:', '["Toward the center","In a circular path","Along the tangent to the circle","Backward"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A body topples when:', '["Its center of gravity falls outside its base","Its weight increases","Friction decreases","Its mass decreases"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A body will be most stable when it has:', '["High center of mass and narrow base","Low center of mass and wide base","High center of mass and wide base","Low center of mass and narrow base"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A bus is more likely to overturn while turning if:', '["It has a low center of gravity","It moves slowly","It has a high center of gravity","Its wheels are wide apart"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The center of gravity of a body is the point where:', '["All forces act","Entire weight appears to act","Friction acts","Torque is maximum"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why are ball bearings used in machines?', '["Increase friction","Reduce weight","Convert sliding friction into rolling friction","Increase torque"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The friction acting between a moving box and the floor is:', '["Static friction","Rolling friction","Sliding friction","Magnetic friction"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A parachutist falling downward at constant velocity is in:', '["Static equilibrium","Dynamic translational equilibrium","Rotational equilibrium only","Accelerated motion"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A body can be in equilibrium even when several forces act on it because:', '["All forces are equal","Net force and net torque are zero","No motion occurs","Gravity is absent"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 50 N force acts at a perpendicular distance of 0.4 m from the pivot. The torque is:', '["10 N·m","20 N·m","25 N·m","125 N·m"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A force of 20 N is applied to a door. Which action produces the greatest torque?', '["Push at the hinge","Push halfway from the hinge","Push at the edge of the door perpendicular to it","Push at the edge parallel to the door"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The SI unit of moment of force is:', '["N/m","Nm","kgm/s²","Joule only"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If the line of action of force passes through the pivot, the turning effect is:', '["Maximum","Minimum","Zero","Infinite"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A body moving with uniform velocity in a straight line is:', '["Not in equilibrium","In translational equilibrium","In rotational equilibrium only","Accelerating"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A picture hanging motionless on a wall is an example of:', '["Dynamic equilibrium","Static equilibrium","Rotational motion","Circular motion"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A body can rotate without translating when:', '["Net force = 0 and torque ≠ 0","Net force ≠ 0 and torque = 0","Both are zero","Neither exists"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why are racing cars built very close to the ground?', '["To reduce mass","To increase speed only","To lower center of gravity","To reduce torque"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which statement is correct?', '["Rolling friction > Sliding friction","Sliding friction > Rolling friction","Both are always equal","Friction never depends on surface type"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which force acts as centripetal force for the Moon revolving around Earth?', '["Magnetic force","Tension force","Gravitational force","Frictional force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A feather and a stone are dropped in air. Which will achieve terminal velocity first?', '["Stone","Feather","Both together","Neither"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A skydiver of mass 80 kg and another of mass 60 kg use identical parachutes. Which has the greater terminal velocity?', '["60 kg diver","80 kg diver","Same terminal velocity","Depends on height"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If Earth''s gravitational force suddenly disappeared, a satellite would:', '["Fall to Earth","Stop immediately","Move in a straight line tangential to its orbit","Move toward the Sun"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A satellite in a circular orbit is accelerating because:', '["Its speed is increasing","Its velocity direction is continuously changing","Its mass is changing","Gravity is increasing"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two satellites orbit Earth at different altitudes. Which has the greater orbital speed?', '["The one closer to Earth","The one farther from Earth","Both have same speed","Depends on mass"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two satellites of masses 500 kg and 1000 kg orbit Earth at the same height. Which has the greater orbital speed?', '["1000 kg satellite","500 kg satellite","Both have same speed","Cannot be determined"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If the distance from the pivot is doubled while the force remains constant, the turning effect will:', '["Halve","Double","Remain unchanged","Become zero"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A light child and a heavy child are balancing a seesaw. If the light child moves farther from the pivot, the seesaw will:', '["Remain balanced","Tilt toward the lighter child","Tilt toward the heavier child","Stop moving"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Frictional force always acts:', '["In the direction of motion","Opposite to the direction of motion","Vertically upward","Toward the center of the Earth"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a falling object reaches terminal velocity, the drag force becomes:', '["Greater than its weight","Less than its weight","Equal to its weight","Zero"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Drag force depends on:', '["Shape of the object only","Speed of the object only","Nature of the fluid only","All of the above"]'::jsonb, 'D', 1);
end $$;
