-- Physics chapter 6 — 36 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 6
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 6: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A student pushes a wall with a force of 200 N for 2 minutes, but the wall does not move. The work done on the wall is:', '["400 J","200 J","0 J","Cannot be determined"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A car and a motorcycle move at the same speed. Which has greater kinetic energy?', '["Motorcycle","Car","Same","Cannot tell"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If speed doubles, kinetic energy becomes:', '["Double","Triple","Four times","Eight times"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 2 kg object moves at 4 m/s. Its kinetic energy is:', '["8 J","16 J","24 J","32 J"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A ball is thrown vertically upward. At the highest point:', '["KE maximum","PE zero","KE zero and PE maximum","Both KE and PE zero"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which is a renewable energy source?', '["Coal","Natural gas","Solar energy","Petroleum"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which energy is stored in food?', '["Sonic","Electrical","Chemical","Nuclear"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two balls are dropped from the same height. One is twice as massive. Just before hitting the ground:', '["Heavier ball has more KE","Same KE","Lighter ball has more KE","Both have zero KE"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A lamp converts electrical energy mostly into:', '["Light and heat","Sound only","Chemical energy","Nuclear energy"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Potential energy depends on:', '["Height","Mass","Gravity","All of these"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which statement is TRUE?', '["Work can be done without force","Work can be done without displacement","Work requires force and displacement","Work depends only on time"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A hydroelectric plant mainly converts:', '["Chemical → Electrical","Nuclear → Electrical","Gravitational PE → Electrical","Heat → Sound"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A machine uses 500 J and delivers 400 J. Efficiency?', '["20%","40%","80%","125%"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 60 W bulb uses 120 J energy in:', '["1 s","2 s","3 s","4 s"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A moving object must possess:', '["Potential energy only","Kinetic energy","Nuclear energy","Chemical energy"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why are renewable sources preferred?', '["Unlimited and environmentally friendly","More expensive only","Produce no energy","Need no technology"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A student lifts a bag slowly and then quickly to the same height. Which is true?', '["More work when lifted quickly","Less work when lifted quickly","Same work done","No work done"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 500 N piano is lifted from 2 m to 8 m. Increase in PE:', '["3000 J","4000 J","5000 J","6000 J"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If momentum of an object becomes 3 times while mass remains constant, kinetic energy becomes:', '["3 times","6 times","9 times","12 times"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two objects have equal momentum. Which one has greater kinetic energy?', '["More massive object","Less massive object","Same KE","Cannot determine"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which unit is equivalent to a joule?', '["N/m","N·m","kg/m²","N²"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which quantity has the same SI unit as work?', '["Force","Momentum","Energy","Power"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The major component of biogas is:', '["Carbon dioxide","Methane","Oxygen","Nitrogen"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Biogas is commonly produced from:', '["Animal dung","Agricultural waste","Organic matter","All of these"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which quantity has unit kg m²/s²?', '["Power","Force","Work","Momentum"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1-Watt equals:', '["1 J × s","1 J/s","1 N/s","1 kg/s"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is NOT a fossil fuel?', '["Coal","Petroleum","Natural Gas","Uranium"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which gas released during fossil fuel combustion contributes most to global warming?', '["Oxygen","Nitrogen","Carbon dioxide","Helium"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which environmental issue is directly linked to excessive fossil fuel use?', '["Deforestation only","Global warming","Earthquakes","Volcanoes"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is a commonly used nuclear fuel?', '["Coal","Uranium-235","Petroleum","Natural gas"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Biogas is produced in the absence of:', '["Water","Oxygen","Carbon dioxide","Sunlight"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The process used in most nuclear power plants is:', '["Fusion","Fission","Distillation","Combustion"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In nuclear fission, a heavy nucleus:', '["Combines with another nucleus","Splits into smaller nuclei","Burns completely","Loses all electrons"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Biogas production helps reduce:', '["Organic waste accumulation","Environmental pollution","Dependence on fossil fuels","All of these"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a nuclear power plant, heat produced by fission is used to:', '["Melt uranium","Produce steam","Freeze water","Burn coal"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The leftover material after biogas production is useful as:', '["Cement","Fertilizer","Coal","Fuel oil"]'::jsonb, 'B', 1);
end $$;
