-- Physics chapter 1 — 32 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 1
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 1: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which quantity is largest?', '["5 mm","5000 μm","0.005 m","All are equal"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which reading has four significant figures?', '["0.0205","2.05","205","20.50"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'This means it can measure:', '["Only whole millimetres","Up to 0.1 mm","Up to 0.01 mm","Up to 1 mm"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The volume of the stone is:', '["15 cm³","40 cm³","55 cm³","95 cm³"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'To reduce random error, he should:', '["Measure one oscillation only.","Measure many oscillations and find the average.","Use a larger pendulum.","Use a ruler."]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A scale always shows 0.2 kg more than the true value. This is an example of:', '["Random error","Systematic error","Human error","Percentage error"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'How many base SI units are there?', '["5","6","7","8"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Round off 5.886 to two decimal places.', '["5.87","5.89","5.80","5.90"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A screw gauge is more precise than a vernier caliper because it has:', '["greater size","more scales","smaller least count","longer spindle"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A reading is written as 8.05 cm. Which digit is uncertain according to the idea of significant figures?', '["8","5","0","All digits equally"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which instrument is most suitable for measuring the internal diameter of a hollow tube?', '["Measuring tape","Meter rule","Vernier caliper","Stopwatch"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which pair contains one scalar and one vector quantity?', '["Speed and velocity","Force and weight","Distance and time","Mass and energy"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The number 3.45 × 10⁷ contains:', '["7 significant figures","3 significant figures","2 significant figures","45 significant figures"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Its diameter in millimeters is:', '["0.2 mm","2 mm","20 mm","200 mm"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The value 5 × 10⁶ m can be written as:', '["5 km","5 Mm","5 μm","5 nm"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The number 0.00072 is written in scientific notation as:', '["7.2 × 10⁻⁵","7.2 × 10⁻⁴","72 × 10⁻⁵","0.72 × 10⁻³"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A student writes 56000 = 5.6 × 10⁻⁴. What is wrong?', '["The coefficient is wrong.","The power of 10 should be positive.","Scientific notation cannot be used.","Nothing is wrong."]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is a physical quantity?', '["Honesty","Happiness","Intelligence","Length"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A measurement without a unit is:', '["Complete","Incomplete","Accurate","Precise"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'This quantity is most likely:', '["Base quantity","Derived quantity","Non-physical quantity","Fundamental quantity"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which part of the measurement changes when the same length is expressed in cm instead of m?', '["Unit only","Numerical magnitude only","Both magnitude and unit","Neither"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A measurement is meaningful only when:', '["It has a large numerical value.","It has a unit.","It has a numerical magnitude and a unit.","It has direction."]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In vector addition, the tail of the second vector is joined to the:', '["Tail of first vector","Head of first vector","Midpoint of first vector","Origin"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The length of a vector arrow represents its:', '["direction","unit","magnitude","position"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which one of the following has SI unit m²?', '["area","volume","speed","density"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The least count of a measuring instrument tells us:', '["its length","its maximum reading","the smallest measurement it can measure","its weight"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which instrument is most suitable for measuring the thickness of a sheet of paper?', '["Measuring tape","Screw gauge","Vernier caliper","Stopwatch"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A measurement taken with a vernier caliper is 6.24 cm. If the main scale reading is 6.2 cm, the coinciding vernier division is:', '["2nd","4th","24th","6th"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If the zero of the vernier scale is to the right of the zero of the main scale, the zero error is', '["Positive","Negative","infinite","zero"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which one of the following is NOT a derived unit?', '["pascal","μm (micrometer)","joule","Newton"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Arrange the following SI prefixes in increasing order of magnitude: Pico, Nano, Milli, Micro', '["Milli, Micro, Nano, Pico","Pico, Nano, Micro, Milli","Nano, Pico, Micro, Milli","Micro, Milli, Nano, Pico"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the "head-to-tail rule" used for?', '["Subtracting vectors","Multiplying vectors","Adding vectors","Finding the magnitude of a single vector"]'::jsonb, 'C', 1);
end $$;
