-- Physics chapter 6 — 59 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 6
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 6: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A football is kicked by a boy which type of energy explain this', '["Solar","Kinetic","Potential","Chemical"]'::jsonb, 'B', 1, '0386cc0ac14c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The shock absorber of motor bike help to absorb energy. Which type of energy is absorbed', '["Kinetic","Potential","Solar","Wind"]'::jsonb, 'A', 1, '34d4b57b94fc', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'We are going on an annual trip in bus which type of energy is converted to kinetic energy of bus', '["Mechanical","Electrical","Physical","Chemical"]'::jsonb, 'D', 1, '645d15c7734e', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In the process of conversion it is not possible to convert all the energy into useful form due to', '["Energy","Work","Displacement","Friction"]'::jsonb, 'D', 1, '6cfa6614f2fb', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If one form of energy is completely converted to other form of energy this is known as', '["Conservation","Conversion","Remain same","All of these"]'::jsonb, 'B', 1, '0a0dcece6588', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If there is a lot of friction is present between the parts of machine kinetic energy is converted into', '["Light","Electrical","Waves","Heat"]'::jsonb, 'D', 1, '2ee4d0ae84ce', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Most of the daily life energy we use can come from which source', '["Renewable","Non renewable","Solar","Sound"]'::jsonb, 'B', 1, '0be75d648e8c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'About 33% of our total non renewable energy is taken from', '["Coal","Natural gas","Nuclear","Petroleum"]'::jsonb, 'D', 1, '98fd34417460', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The motion of a body that continues forever in an undisturbed system is called', '["Perpendicular","Powerful","Point range","Perpetual"]'::jsonb, 'D', 1, 'bc503a784425', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The ideal machine in which there is no friction present in their part is known as', '["Hypothetical machine","Hyper machine","Hypothesis machine","Hygiene machine"]'::jsonb, 'A', 1, 'f6495a035a78', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which is the most abundant for sale fuel globally', '["Coal","Oil","Natural gas","All of them"]'::jsonb, 'A', 1, '0cf1912bddc0', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which material undergoes refining and yield gasoline', '["Coal tar","Natural gas","Crude oil","All of them"]'::jsonb, 'C', 1, 'ec0eb99f9cc2', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Oil and natural gas are usually extracted from underground reservoirs by', '["Mining","Drilling","Digging","Extraction"]'::jsonb, 'B', 1, '5dc0c916fa42', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Nuclear power plant harnesses the energy in the nucleus of an atom through process of', '["Fission","Fusion","Burning","Lightning"]'::jsonb, 'A', 1, 'da117e98166c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Nuclear power plant used which of the radioactive material to produce electricity', '["Uranium -235","Polonium -238","Uranium -239","All of them"]'::jsonb, 'A', 1, '583ce47d86a4', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'What is the primary component of natural gas', '["Carbon dioxide","Methane","Ethanol","Nitrogen"]'::jsonb, 'B', 1, '574e84735680', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The rate of doing work with respect to time is called', '["Pressure","Density","Power","Efficiency"]'::jsonb, 'C', 1, 'e750db81b305', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which type of quantity power is', '["Vector","Scalar","Base","Non of these"]'::jsonb, 'B', 1, '8f0206d7b93d', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If a water motor is utilizing a power of 1120 W how many hp are there in it.', '["1 hp","2.5 hp","1.5 hp","2.7 ho"]'::jsonb, 'C', 1, '5c9fd207699c', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'What is the unit for efficiency', '["Watt","Joules","Newton","No unit"]'::jsonb, 'D', 1, 'a0022d93be6f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Efficiency of system is always calculated in', '["Kilo watt","Horse power","Percentage","Kilo joules"]'::jsonb, 'C', 1, '0c37b6c14d3f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Power rating of an electric devices is considered as', '["Voltage","Current","Resistance","Wattage"]'::jsonb, 'D', 1, '8983966ae614', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Physicists have calculated that rise and fall of tides dissipate energy at the rate of about', '["10 million megawatt","5 million megawatt","4 million megawatt","2 million megawatt"]'::jsonb, 'C', 1, 'c5f8aa4cd5e9', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A student pushes a wall with a force of 200 N for 2 minutes, but the wall does not move. The work done on the wall is:', '["400 J","200 J","0 J","Cannot be determined"]'::jsonb, 'C', 1, '14db1ee28274', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A car and a motorcycle move at the same speed. Which has greater kinetic energy?', '["Motorcycle","Car","Same","Cannot tell"]'::jsonb, 'B', 1, '1a0975f5bc9a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If speed doubles, kinetic energy becomes:', '["Double","Triple","Four times","Eight times"]'::jsonb, 'C', 1, '148a292256d3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 2 kg object moves at 4 m/s. Its kinetic energy is:', '["8 J","16 J","24 J","32 J"]'::jsonb, 'B', 1, 'd5c4473f23e9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A ball is thrown vertically upward. At the highest point:', '["KE maximum","PE zero","KE zero and PE maximum","Both KE and PE zero"]'::jsonb, 'C', 1, '802bf59e6004', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which is a renewable energy source?', '["Coal","Natural gas","Solar energy","Petroleum"]'::jsonb, 'C', 1, 'd51cb8ede31a', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which energy is stored in food?', '["Sonic","Electrical","Chemical","Nuclear"]'::jsonb, 'C', 1, '0a300b6dff06', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two balls are dropped from the same height. One is twice as massive. Just before hitting the ground:', '["Heavier ball has more KE","Same KE","Lighter ball has more KE","Both have zero KE"]'::jsonb, 'A', 1, 'def499041feb', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A lamp converts electrical energy mostly into:', '["Light and heat","Sound only","Chemical energy","Nuclear energy"]'::jsonb, 'A', 1, '71dd4cfe0086', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Potential energy depends on:', '["Height","Mass","Gravity","All of these"]'::jsonb, 'D', 1, '0b0b31e9bade', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which statement is TRUE?', '["Work can be done without force","Work can be done without displacement","Work requires force and displacement","Work depends only on time"]'::jsonb, 'C', 1, 'aa8a4c98d22d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A hydroelectric plant mainly converts:', '["Chemical → Electrical","Nuclear → Electrical","Gravitational PE → Electrical","Heat → Sound"]'::jsonb, 'C', 1, '0743ab19d27e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A machine uses 500 J and delivers 400 J. Efficiency?', '["20%","40%","80%","125%"]'::jsonb, 'C', 1, '94fdf8ae00fd', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 60 W bulb uses 120 J energy in:', '["1 s","2 s","3 s","4 s"]'::jsonb, 'B', 1, '9e0265ebe535', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A moving object must possess:', '["Potential energy only","Kinetic energy","Nuclear energy","Chemical energy"]'::jsonb, 'B', 1, '2a86288d1e37', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Why are renewable sources preferred?', '["Unlimited and environmentally friendly","More expensive only","Produce no energy","Need no technology"]'::jsonb, 'A', 1, '8230bd297fcc', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A student lifts a bag slowly and then quickly to the same height. Which is true?', '["More work when lifted quickly","Less work when lifted quickly","Same work done","No work done"]'::jsonb, 'C', 1, '413cbd1a75ef', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A 500 N piano is lifted from 2 m to 8 m. Increase in PE:', '["3000 J","4000 J","5000 J","6000 J"]'::jsonb, 'A', 1, 'c4478b245f14', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If momentum of an object becomes 3 times while mass remains constant, kinetic energy becomes:', '["3 times","6 times","9 times","12 times"]'::jsonb, 'C', 1, 'e066de6ba2db', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Two objects have equal momentum. Which one has greater kinetic energy?', '["More massive object","Less massive object","Same KE","Cannot determine"]'::jsonb, 'B', 1, '16164404bbf2', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which unit is equivalent to a joule?', '["N/m","N·m","kg/m²","N²"]'::jsonb, 'B', 1, 'c7d967f12bb8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which quantity has the same SI unit as work?', '["Force","Momentum","Energy","Power"]'::jsonb, 'C', 1, '6ca7bd9dc33f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The major component of biogas is:', '["Carbon dioxide","Methane","Oxygen","Nitrogen"]'::jsonb, 'B', 1, '8827a6099632', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Biogas is commonly produced from:', '["Animal dung","Agricultural waste","Organic matter","All of these"]'::jsonb, 'D', 1, '603da31e9cb3', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which quantity has unit kg m²/s²?', '["Power","Force","Work","Momentum"]'::jsonb, 'C', 1, '16edae7e6aed', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1-Watt equals:', '["1 J × s","1 J/s","1 N/s","1 kg/s"]'::jsonb, 'B', 1, 'd5f1f01a1380', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is NOT a fossil fuel?', '["Coal","Petroleum","Natural Gas","Uranium"]'::jsonb, 'D', 1, 'f2fc1356d90c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which gas released during fossil fuel combustion contributes most to global warming?', '["Oxygen","Nitrogen","Carbon dioxide","Helium"]'::jsonb, 'C', 1, 'a56f99f73d84', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which environmental issue is directly linked to excessive fossil fuel use?', '["Deforestation only","Global warming","Earthquakes","Volcanoes"]'::jsonb, 'B', 1, '4c44443d3c28', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is a commonly used nuclear fuel?', '["Coal","Uranium-235","Petroleum","Natural gas"]'::jsonb, 'B', 1, 'ade77f3a7237', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Biogas is produced in the absence of:', '["Water","Oxygen","Carbon dioxide","Sunlight"]'::jsonb, 'B', 1, 'f30265dd323f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The process used in most nuclear power plants is:', '["Fusion","Fission","Distillation","Combustion"]'::jsonb, 'B', 1, '1f8ab80a0c44', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In nuclear fission, a heavy nucleus:', '["Combines with another nucleus","Splits into smaller nuclei","Burns completely","Loses all electrons"]'::jsonb, 'B', 1, '64e5a9af430e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Biogas production helps reduce:', '["Organic waste accumulation","Environmental pollution","Dependence on fossil fuels","All of these"]'::jsonb, 'D', 1, 'ac97a306e068', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'In a nuclear power plant, heat produced by fission is used to:', '["Melt uranium","Produce steam","Freeze water","Burn coal"]'::jsonb, 'B', 1, 'fbcafd3cba5f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The leftover material after biogas production is useful as:', '["Cement","Fertilizer","Coal","Fuel oil"]'::jsonb, 'B', 1, '6a501ecb5d2f', null);
end $$;
