-- Physics chapter 5 — 31 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 5
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 5: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is an example of an elastic material?', '["Clay","Dough","Stretched spring","Plasticine"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Beyond the elastic limit, a material:', '["Always breaks immediately","Returns completely to original shape","Does not fully regain its original dimensions","Loses mass"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The correct mathematical expression of Hooke''s law is:', '["F= x/k","F= −kx","F= k /x","F= kx2"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The SI unit of spring constant is:', '["N","Pa","N/m","kg/m³"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The slope of a force-extension graph gives:', '["Pressure","Density","Spring constant","Weight"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Hooke’s law is obeyed up to:', '["Limit of proportionality","Plastic limit","Breaking point","Yield point"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The “tick” sound in a mechanical watch is due to:', '["Random vibration","Friction only","Regular oscillation of balance wheel","Electrical pulses"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A spring extends 4 cm under a force of 20 N. Under 40 N, the extension will be:', '["2 cm","4 cm","8 cm","16 cm"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The maximum stress a material can withstand before fracture is:', '["Elastic stress","Ultimate stress","Pressure stress","Hydrostatic stress"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The SI unit of pressure is:', '["Newton","Joule","Pascal","Watt"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1 Pascal equals:', '["1 N/m²","1 N/m","1 kg/m²","1 J/m²"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pressure increases when:', '["Area increases","Force decreases","Force increases on same area","Mass decreases"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A balloon bursts easily when pierced by a pin because:', '["Pin is heavy","Pin applies high pressure on small area","Balloon loses weight","Air pressure becomes zero"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A sharp knife cuts better because it:', '["Has greater mass","Produces less pressure","Produces greater pressure due to smaller area","Is longer"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A person stands on one foot instead of two. The pressure on the ground:', '["Halves","Doubles","Remains same","Becomes zero"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a person of mass 50 kg sits on a spring chair and compresses the spring by 0.1m, what is the calculated spring constant k of the chair’s spring? (Take g = 9.8 m/s2)', '["490 N/m","4,900 N/m","980 N/m","49,000 N/m"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A mountain climber moves to higher altitude. Atmospheric pressure will:', '["Increase","Remain constant","Decrease","Become zero immediately"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'One bar equals:', '["10³ Pa","10⁴ Pa","10⁵ Pa","10⁶ Pa"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1 atmosphere (atm) is equal to:', '["760 mmHg","76 mmHg","7.6 mmHg","7600 mmHg"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A liquid barometer is used to measure:', '["Liquid pressure only","Atmospheric pressure","Density","Humidity"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A mercury barometer works on the principle of:', '["Reflection","Hydrostatic equilibrium","Electromagnetism","Conduction"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The unit torr is equivalent to:', '["1 atm","1 Pa","1 mmHg","1 bar"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pascal''s law states that pressure applied to a confined fluid is:', '["Lost completely","Transmitted equally in all directions","Reduced by half","Converted into heat"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A mechanic uses a hydraulic jack to lift a heavy car with a small effort. This is possible because:', '["Hooke''s law","Pascal''s law","Newton''s first law","Archimedes'' principle"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The unit for pressure commonly used in weather maps is the millibar (mbar). One millibar 1 mbar is equal to:', '["1Pa","10Pa","100 Pa","1,000 Pa"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Drinking through a straw is made possible because the action of sucking achieves which of the following?', '["It increases the atmospheric pressure outside the straw.","It increases the pressure inside the mouth.","It lowers the pressure in the mouth below atmospheric pressure.","It changes the density of the liquid being consumed."]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a deforming force is removed and an object regains its original shape, the property is called:', '["Plasticity","Elasticity","Rigidity","Pressure"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Three holes are made in a water tank at different depths. Water comes out fastest from:', '["Top hole","Middle hole","Lowest hole","All equally"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pressure in a liquid depends on:', '["Depth and density","Shape of container only","Volume only","Color of liquid"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If both force and area are doubled, pressure will:', '["Double","Halve","Remain unchanged","Become four times"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pressure is inversely proportional to:', '["Force","Mass","Density","Area"]'::jsonb, 'D', 1);
end $$;
