-- Physics chapter 2 — 34 MCQs from the owner's bank.
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 2
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 2: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks)
  values
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which type of motion is exhibited by a freely falling body?', '["Circular Motion","Linear Motion","Rotatory Motion","Vibrational Motion"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'An athlete runs exactly one complete lap around a circular running track of radius R. What are the values of distance (s) and displacement (Δd) respectively?', '["s = 0, Δd = 2πR","s = 2πR, Δd = 0","s = πR², Δd = 2R","s = 2R, Δd = 0"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a commuter travels 10 km due North, then makes a sharp right turn and drives 10 km due East, what is the total distance covered and the net displacement?', '["Distance = 20 km, Displacement = 20 km","Distance = 14.14 km, Displacement = 20 km","Distance = 20 km, Displacement = 14.14 km North-East","Distance = 0 km, Displacement = 10 km"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A delivery truck travels along a winding track of length 1200 m in 60 seconds. The straight-line distance from its starting warehouse to its destination is 600 m. What is its average speed?', '["10 m/s","20 m/s","30 m/s","5 m/s"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'An object is moving with a constant velocity of +15 m/s along a straight runway. What is its acceleration?', '["+15 m/s²","-15 m/s²","Zero","Dependent on the total time elapsed"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A sports car accelerates uniformly from 10 m/s to 30 m/s over a time interval of 5 seconds. What is the precise rate of change of its velocity?', '["8 m/s²","4 m/s²","6 m/s²","2 m/s²"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'When an object is dropped in a true vacuum environment near Earth’s surface, its downward acceleration is:', '["Dependent on the object’s total surface area profile","Directly proportional to the mass of the object","Constant at approximately 9.8 m/s², regardless of mass values","Progressively decreasing as the object gains velocity"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a heavy iron ball and a light wooden ball are dropped simultaneously from the top of a tall tower in a vacuum chamber, which ball strikes the base first?', '["The heavy iron ball hits significantly earlier","The light wooden ball hits significantly earlier","Both balls strike the base at the exact same instant","It depends heavily on which ball was released with more force"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'An object is dropped from rest from the edge of a high cliff. Assuming g = 10 m/s² for calculation ease, what will be its downward speed after exactly 3 seconds of free fall?', '["15 m/s","30 m/s","45 m/s","9.8 m/s"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The study of motion without considering the forces involved is called:', '["Dynamics","Statics","Kinematics","Thermodynamics"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is an example of rotatory motion?', '["A car moving on a road","A wheel spinning about its axle","A ball falling from a height","A person walking"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a car is traveling westward along a straight highway and applies its brakes to slow down, what are the directions of its velocity and acceleration vectors respectively?', '["Velocity is West, Acceleration is West","Velocity is East, Acceleration is West","Velocity is West, Acceleration is East","Both vectors drop instantly to zero"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is the correct formula for speed?', '["Speed = Time / Distance","Speed = Distance x Time","Speed = Distance / Time","Speed = Time x Acceleration"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When does an object accelerate?', '["Only when its speed increases","Only when its speed decreases","Only when its direction of motion changes","When there is a change in its speed, direction, or both"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a car is traveling around a circular track at a constant speed of 50 km/h, is it accelerating?', '["Yes, because its direction is constantly changing","No, because the speed is constant","No, because the velocity is constant","Yes, because the distance is increasing"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'What is the SI unit of acceleration?', '["m/s","m/s²","m/s³","kg/m³"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The area under a speed–time graph represents:', '["Speed","Volume","Acceleration","Distance"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A particle starts from rest and achieves a velocity of 24 m/s in a span of 6 seconds along a linear track. What is its average acceleration?', '["4 m/s²","144 m/s²","2 m/s²","0.25 m/s²"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a body covers equal distance in equal intervals of time, then the speed of the body is known as:', '["Uniform","Variable","Non uniform","All of these"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a satellite is moving in a circle with constant speed, its velocity will be:', '["Uniform","Constant","Variable","All of these"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If the velocity of the body is decreasing then its acceleration will be:', '["Positive","Negative","Zero","Uniform"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If the velocity of the body is increasing then its acceleration will be:', '["Positive","Negative","Zero","Non-uniform"]'::jsonb, 'A', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If the velocity of a body is uniform then its acceleration will be:', '["Positive","Negative","Zero","Doubled"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A passenger train traveling eastward along a straight track begins to slow down as it approaches a station. The direction of the train''s acceleration is:', '["Toward the East","Toward the West","Vertically downward","It has no direction because it is slowing down"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'An airplane is flying toward the Southeast when the pilot throttles back the engines, causing the plane to slow down. The direction of the aircraft''s acceleration is toward the:', '["Southeast","Northwest","Southwest","Northeast"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A driver presses the gas pedal of a car moving along a straight highway, causing it to speed up in the forward direction. In this situation, the car''s acceleration is:', '["Negative","Positive","Zero","Non-uniform"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A speed-time graph features a straight line sloping downward toward the right. This represents:', '["Uniform acceleration","Uniform deceleration","Non-uniform acceleration","Constant speed"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a distance-time graph shows a curved line that bends gradually upward (getting steeper), the motion of the body can be described as:', '["Uniform speed","Constant velocity","Non-uniform speed where the object is speeding up","Non-uniform speed where the object is slowing down"]'::jsonb, 'C', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The slope (or gradient) of a distance-time graph directly represents which physical quantity?', '["Displacement","Acceleration","Distance","Speed"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If the distance-time graph of a moving object is a perfectly flat, horizontal line parallel to the time axis, it indicates that:', '["The object is moving with constant speed","The object is at complete rest","The object is moving with uniform acceleration","The object is returning back to its starting point"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'An object is thrown vertically straight upward into the air. At the highest point of its flight, the object’s velocity and acceleration are:', '["Velocity is zero, and acceleration is zero","Velocity is zero, and acceleration is equal to acceleration due to gravity","Velocity is maximum, and acceleration is zero","Velocity is maximum, and acceleration is equal to acceleration due to gravity"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The gradient (slope) of speed time curve gives magnitude of:', '["Distance","Speed","Time","Acceleration"]'::jsonb, 'D', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The speedometer of a car shows:', '["Average speed","Instantaneous speed","Uniform acceleration","Total distance"]'::jsonb, 'B', 1),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The motion of a guitar string when plucked is an example of:', '["Linear motion","Circular motion","Vibratory motion","Random motion"]'::jsonb, 'C', 1);
end $$;
