-- Physics chapter 5 — 55 MCQs (0 variants).
-- Generated by scripts/load-mcq-bank.mjs --sql. Safe to re-run.
do $$
declare v_chapter uuid;
begin
  select c.id into v_chapter
  from chapters c
  join books b on b.id = c.book_id
  join subjects s on s.id = b.subject_id
  where s.name = 'Physics' and c.seq = 5
  limit 1;

  if v_chapter is null then
    raise notice 'skipping Physics chapter 5: not found';
    return;
  end if;

  delete from questions where chapter_id = v_chapter and source = 'bank';

  insert into questions (chapter_id, type, category, source, difficulty, stem_md, options_json, answer_key_md, marks, family, explanation_md)
  values
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Which state of matter required a large force for deformation', '["Solid","Liquid","Gas","Plasma"]'::jsonb, 'A', 1, '2eef86c59afb', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'When a tennis racket hits a ball the shape of ball is distorted and regain its original shape this property is', '["Pressure","Deformation","Elasticity","Density"]'::jsonb, 'C', 1, '0bf1d7d36d69', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A girl is playing with clay and after pressing it is completely deformed we said this material as', '["Elastic","Plastic","Liquid","Gas"]'::jsonb, 'B', 1, 'd60c31114fd4', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If the applied force exceeds the limit of proportionality in hooks law force and extension are no longer directly positional and the graph become', '["Straight","Curve","Proportional","None of these"]'::jsonb, 'B', 1, 'e7c11b4fbde2', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A teacher wears high-heeled shoes one day and flat shoes the next day. Which shoes exert more pressure on the floor?', '["Heel shoes","Flat shoes","Both have same","Both have no pressure"]'::jsonb, 'A', 1, 'c511d86f8242', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Flat shoes exert much less pressure than high heels because their area is', '["Small","Large","Equal","No Area"]'::jsonb, 'B', 1, '16ca5bb0152b', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A suction cup sticks to a wall easily due to', '["Water pressure","Solid pressure","Atmospheric pressure","Liquid pressure"]'::jsonb, 'C', 1, '0e9fde8c7072', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'At sea level the atmosphere will push down mercury in the tube and make it rise up in a tube to a height of approximately', '["29.92 mm","560 mm","670 mm","760 mm"]'::jsonb, 'D', 1, '6e0057e4a4d8', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The height of Mount Everest from the sea level is approximately equal to', '["4.4 km","6.8 km","8.8 km","9.4 km"]'::jsonb, 'C', 1, '6263f70bfac8', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Galvanometer meter is a device in which hooks law is applicable for which purpose this device is used', '["Charge","Current","Emf","All of them"]'::jsonb, 'B', 1, '0a10cbee7300', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If the mass of a person sitting on a chair is doubled what would be the effect on pressure on chair', '["Double","Four times","Three times","Half"]'::jsonb, 'A', 1, '0e36af89574e', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The unit of pressure which is used in metrology and whether maps is', '["Tar","Newton","Bar","Pascal"]'::jsonb, 'C', 1, '9a9959322442', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The liquid barometer works on a principal of', '["Hydrostatic equilibrium","Stable equilibrium","Unstable equilibrium","Neutral equilibrium"]'::jsonb, 'A', 1, 'd450912d23f7', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If we are climbing a mushkpuri track we feel suffocation this is due to', '["Low atmospheric pressure","High atmospheric pressure","Zero atmospheric pressure","Due to more oxygen"]'::jsonb, 'A', 1, '542593050ad0', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'The atmospheric pressure is decreases with height due to decrease in', '["Power","Energy","Density","Force"]'::jsonb, 'C', 1, '56371e08bf7f', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If we have two containers one is filled with water and other is filled with Mercury and we place a stone in each container one after another the change in liquid pressure is due to', '["Gravity","Depth","Color","Density"]'::jsonb, 'D', 1, 'd7f8e39c08da', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'When you dive in the sea, the force exerted on you by the pressure of the water acts', '["Parallel","Perpendicular","Anti parallel","None of these"]'::jsonb, 'B', 1, 'c45036628063', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a device in which pressure is applicable by a force on unit area . Which law describe this', '["Newton''s law","Pascal''s law","Archimedes principal","All of these"]'::jsonb, 'B', 1, 'f34b7cd04d9e', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A scuba diver goes deep into the sea to see marine life. The high pressure the diver experiences is due to', '["Density","Volume","Gravity","Depth"]'::jsonb, 'D', 1, '4917b4372012', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'If the force applied on the brake pedal of a car is doubled over the same area, the pressure', '["Half","Three time","Five times","Double"]'::jsonb, 'D', 1, 'fbe9ab074774', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'In a DG cement factory there is a chiller power plant filled with oil if the engineers want to check the pressure of oil which device would be suitable', '["Barometer","Manometer","Thermometer","Voltmeter"]'::jsonb, 'B', 1, '93e4e7688f90', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'One bar is the unit of atmospheric pressure how many pascal are there in one bar', '["1 x 10²","1 x10 ⁵","1x10 ⁶","1x 10 ⁸"]'::jsonb, 'B', 1, 'af59945707b7', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'A sudden fall in the reading of a barometer usually indicates', '["Dry weather","Storm","High liquid pressure","Expansion of Mercury"]'::jsonb, 'B', 1, '3eea73599354', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Three holes are drilled at different heights in a can full of water. Water spurts out fastest and furthest from which hole?', '["Lower","Upper","Middle","All"]'::jsonb, 'A', 1, '49f77af3ca1a', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 5, 'Three holes are drilled at different heights in a can full of water. Water spurts out slowest and nearest from which hole?', '["Upper","Middle","Lower","All"]'::jsonb, 'A', 1, '36a02cbd72cb', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Which of the following is an example of an elastic material?', '["Clay","Dough","Stretched spring","Plasticine"]'::jsonb, 'C', 1, '8b529f1e41c7', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Beyond the elastic limit, a material:', '["Always breaks immediately","Returns completely to original shape","Does not fully regain its original dimensions","Loses mass"]'::jsonb, 'C', 1, 'd5249baf627d', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The correct mathematical expression of Hooke''s law is:', '["F= x/k","F= −kx","F= k /x","F= kx²"]'::jsonb, 'B', 1, 'ad12448eb002', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The SI unit of spring constant is:', '["N","Pa","N/m","kg/m³"]'::jsonb, 'C', 1, '779237562f49', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The slope of a force-extension graph gives:', '["Pressure","Density","Spring constant","Weight"]'::jsonb, 'C', 1, '6363299e6a29', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Hooke’s law is obeyed up to:', '["Limit of proportionality","Plastic limit","Breaking point","Yield point"]'::jsonb, 'A', 1, '115b002f0bff', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A spring extends 4 cm under a force of 20 N. Under 40 N, the extension will be:', '["2 cm","4 cm","8 cm","16 cm"]'::jsonb, 'C', 1, '825e651f712e', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The maximum stress a material can withstand before fracture is:', '["Elastic stress","Ultimate stress","Pressure stress","Hydrostatic stress"]'::jsonb, 'B', 1, '3ef57a570952', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The SI unit of pressure is:', '["Newton","Joule","Pascal","Watt"]'::jsonb, 'C', 1, 'c94d54ca9da0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1 Pascal equals:', '["1 N/m²","1 N/m","1 kg/m²","1 J/m²"]'::jsonb, 'A', 1, 'bbc0eca860d8', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pressure increases when:', '["Area increases","Force decreases","Force increases on same area","Mass decreases"]'::jsonb, 'C', 1, '2adbf79c1aff', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A balloon bursts easily when pierced by a pin because:', '["Pin is heavy","Pin applies high pressure on small area","Balloon loses weight","Air pressure becomes zero"]'::jsonb, 'B', 1, 'ae26701a2988', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A sharp knife cuts better because it:', '["Has greater mass","Produces less pressure","Produces greater pressure due to smaller area","Is longer"]'::jsonb, 'C', 1, 'd913241022e0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A person stands on one foot instead of two. The pressure on the ground:', '["Halves","Doubles","Remains same","Becomes zero"]'::jsonb, 'B', 1, '27db26a44096', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'If a person of mass 50 kg sits on a spring chair and compresses the spring by 0.1m, what is the calculated spring constant k of the chair’s spring? (Take g = 9.8 m/s²)', '["490 N/m","4,900 N/m","980 N/m","49,000 N/m"]'::jsonb, 'B', 1, 'a7bb0c38e0d4', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A mountain climber moves to higher altitude. Atmospheric pressure will:', '["Increase","Remain constant","Decrease","Become zero immediately"]'::jsonb, 'C', 1, 'c6e5c1981c3c', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'One bar equals:', '["10³ Pa","10⁴ Pa","10⁵ Pa","10⁶ Pa"]'::jsonb, 'C', 1, '2804c7d2ead0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, '1 atmosphere (atm) is equal to:', '["760 mmHg","76 mmHg","7.6 mmHg","7600 mmHg"]'::jsonb, 'A', 1, '78247c956c08', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A liquid barometer is used to measure:', '["Liquid pressure only","Atmospheric pressure","Density","Humidity"]'::jsonb, 'B', 1, '5d68d0667781', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'A mercury barometer works on the principle of:', '["Reflection","Hydrostatic equilibrium","Electromagnetism","Conduction"]'::jsonb, 'B', 1, 'f066f7cf19f9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The unit torr is equivalent to:', '["1 atm","1 Pa","1 mmHg","1 bar"]'::jsonb, 'C', 1, 'ce6f33fef625', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pascal''s law states that pressure applied to a confined fluid is:', '["Lost completely","Transmitted equally in all directions","Reduced by half","Converted into heat"]'::jsonb, 'B', 1, 'cd307cc0c60a', null),
    (v_chapter, 'mcq', 'scenario', 'bank', 3, 'A mechanic uses a hydraulic jack to lift a heavy car with a small effort. This is possible because:', '["Hooke''s law","Pascal''s law","Newton''s first law","Archimedes'' principle"]'::jsonb, 'B', 1, '831bb904ce74', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'The unit for pressure commonly used in weather maps is the millibar (mbar). One millibar 1 mbar is equal to:', '["1Pa","10Pa","100 Pa","1,000 Pa"]'::jsonb, 'C', 1, '51905a7908a9', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Drinking through a straw is made possible because the action of sucking achieves which of the following?', '["It increases the atmospheric pressure outside the straw.","It increases the pressure inside the mouth.","It lowers the pressure in the mouth below atmospheric pressure.","It changes the density of the liquid being consumed."]'::jsonb, 'C', 1, 'c795b0455a4f', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'When a deforming force is removed and an object regains its original shape, the property is called:', '["Plasticity","Elasticity","Rigidity","Pressure"]'::jsonb, 'B', 1, 'b184b035b997', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Three holes are made in a water tank at different depths. Water comes out fastest from:', '["Top hole","Middle hole","Lowest hole","All equally"]'::jsonb, 'C', 1, 'c3094abc8fc1', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pressure in a liquid depends on:', '["Depth and density","Shape of container only","Volume only","Color of liquid"]'::jsonb, 'A', 1, '90a215aed81b', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'If both force and area are doubled, pressure will:', '["Double","Halve","Remain unchanged","Become four times"]'::jsonb, 'C', 1, '8de966cb16b0', null),
    (v_chapter, 'mcq', 'concept', 'bank', 3, 'Pressure is inversely proportional to:', '["Force","Mass","Density","Area"]'::jsonb, 'D', 1, '2c1a6cfa3215', null);
end $$;
