-- Auto-generated by scripts/gen-seed-chapters.mjs from content/chapters-9.json.
-- Idempotent: safe to re-run. Ensures the five offered subjects, drops the rest,
-- and adds any missing chapter rows (matched on book + seq).
do $$
declare
  v_json    jsonb := $hf${"class_level":9,"subjects":[{"subject":"Chemistry","chapters":["Nature of Science in Chemistry","Matter","Atomic Structure","Periodic Table and Periodicity of Properties","Chemical Bonding","Stoichiometry","Electrochemistry","Energetics","Chemical Equilibrium","Acids, Bases and Salts","Environmental Chemistry — Air","Environmental Chemistry — Water","Organic Chemistry","Hydrocarbons","Biochemistry"]},{"subject":"Computer Science","chapters":["Computer Systems","Computational Thinking & Algorithms","Programming Fundamentals","Data and Analysis","Application of Computer Science","Impacts of Computing","Entrepreneurship"]},{"subject":"Maths","chapters":["Real Numbers","Logarithms","Sets and Relations","Factorization and Algebraic Manipulation","Linear Equations and Inequalities","Trigonometry and Bearing","Coordinate Geometry","Geometry of Straight Lines","Geometry and Polygons","Practical Geometry","Basic Statistics"]},{"subject":"English","chapters":["Hazrat Muhammad Rasulullah ﷺ — A Mercy for All Creation","The Art of Muslim Women's Entrepreneurship","Modern World and Age of Digital Globalization","Nothing is Impossible — The Construction of Spectacular Brooklyn Bridge","5 of Jeff Bezos's Best Lessons for Success","Say No to Drugs","Mowing by Robert Frost","The Eagle by Alfred Tennyson","Travel and Tourism","Two Mothers Remembered by Joann Snow Duncanson","The Metamorphosis","Good Health and Well Being"]}]}$hf$::jsonb;
  v_class   int   := (v_json->>'class_level')::int;
  v_subject uuid;
  v_book    uuid;
  v_name    text;
  sub jsonb;
  ch  jsonb;
  i   int;
begin
  -- 1. Ensure every offered subject exists.
  foreach v_name in array array['Physics', 'Chemistry', 'Maths', 'Computer Science', 'English']
  loop
    if not exists (select 1 from subjects where name = v_name) then
      insert into subjects(name) values (v_name);
    end if;
  end loop;

  -- 2. Remove subjects Prepify no longer teaches (clear enrolments first, since
  --    enrollments.subject_id has no cascade).
  delete from enrollments
   where subject_id in (select id from subjects where name = any(array['Biology', 'Islamiyat', 'Pak Studies', 'Urdu']));
  delete from subjects where name = any(array['Biology', 'Islamiyat', 'Pak Studies', 'Urdu']);

  -- 3. Chapters per subject.
  for sub in select jsonb_array_elements(v_json->'subjects') loop
    select id into v_subject from subjects where name = sub->>'subject';
    if v_subject is null then
      raise exception 'Subject % missing', sub->>'subject';
    end if;

    select id into v_book from books
      where subject_id = v_subject and class_level = v_class
      order by id limit 1;
    if v_book is null then
      insert into books(subject_id, class_level, edition)
        values (v_subject, v_class, 'FBISE') returning id into v_book;
    end if;

    i := 0;
    for ch in select jsonb_array_elements(sub->'chapters') loop
      i := i + 1;
      if not exists (select 1 from chapters where book_id = v_book and seq = i) then
        insert into chapters(book_id, seq, title) values (v_book, i, ch #>> '{}');
      end if;
    end loop;
  end loop;
end $$;
